import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, defaultValue?: string) => string;
  dir: 'ltr' | 'rtl';
  isAr: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Sidebar & Navigation
    'revive_clinic': 'REVIVE Clinic',
    'dashboard': 'Dashboard',
    'recovery_monitoring': 'Recovery Monitoring',
    'calendar': 'Calendar',
    'patients': 'Patients',
    'reports': 'Reports',
    'finance': 'Finance',
    'clinic_assessment': 'Clinic Assessment',
    'exercise_library': 'Exercise Library',
    'investigation_library': 'Investigation Library',
    'ai_assist': 'Revive AI Assist',
    'account_requests': 'Account Requests',
    'shift_attendance': 'Shift Attendance',
    'settings_backup': 'Settings & Backup',
    'logout': 'Log Out',
    'version': 'Version',
    'user': 'User',
    'branch': 'Branch',
    'switch_branch': 'Switch Branch',
    'home': 'Home',
    'schedule': 'Schedule',
    'menu': 'Menu',

    // Settings
    'system_settings': 'System Settings',
    'settings_subtitle': 'Configure clinical protocols, user accounts, and system logistics.',
    'db_backup': 'Database & Backup',
    'whatsapp_templates': 'WhatsApp Templates',
    'team_management': 'Team Management',
    'branches': 'Branches',
    'data_persistence': 'Data Persistence',
    'db_backup_desc': 'Generate a full encrypted export of the local SQLite database. This includes all patient records, clinical history, and system configurations.',
    'export_backup': 'Export Local Backup',
    'network_db': 'Network Database',
    'network_db_desc': 'Configure a shared database path across your network. This allows multiple workstations to access and update the same clinical data simultaneously.',
    'active_db_loc': 'Active Database Location:',
    'select_shared_db': 'Select Shared Database',
    'financial_period': 'Financial Period',
    'financial_period_desc': 'Reset the current dashboard revenue tracking. This will start a new fiscal period or month. Existing clinical records remain untouched.',
    'reset_period': 'Reset Analysis Period',
    'whatsapp_reminder': 'WhatsApp Reminder Template',
    'whatsapp_reminder_desc': 'Customize the default message sent to patients for confirmations',
    'whatsapp_review': 'WhatsApp Review Template',
    'whatsapp_review_desc': 'Customize the default message sent to patients after session is completed',
    'template_text': 'Template Message Text',
    'dynamic_tokens': 'Dynamic Placeholder Tokens:',
    'dynamic_tokens_desc': 'Use these tags to automatically fill in details from the appointment:',
    'save_templates': 'Save Templates',
    'loading_path': 'Loading path...',

    // Dashboard
    'today_appts': 'Today\'s Appointments',
    'total_patients': 'Total Patients',
    'active_staff': 'Active Staff',
    'revenue': 'Revenue',
    'active_sessions': 'Active Sessions',
    'diagnostic_tests': 'Diagnostic Tests',
    'high_pain_alerts': 'High Pain Alerts',
    'search_patients': 'Search Patients...',
    'loading_branch': 'Loading Branch Data...',
    'switch_branch_btn': 'Switch Branch',
    'clinical_dashboard': 'Clinical Dashboard',
    'dashboard_subtitle': 'Real-time patient monitoring and practice metrics.',
    'recovery_monitoring_subtitle': 'Real-time patient clinical pain assessments.',
    'session': 'Session',
    'all_time': 'All Time',
    'critical_pain_alerts': 'Critical Pain Alerts',
    'urgent_attention': 'Urgent Attention',
    'daily_queue': 'Daily Queue',
    'scheduled': 'Scheduled',
    'active_load': 'Active Load',
    'in_system': 'In System',
    'performance': 'Performance',
    'elite_management': 'Elite Clinical Management',
    'elite_management_desc': 'Secure Database Syncing. AI Clinical Analysis. Automated Patient Feedback Loop.',
    'manage_patients': 'Manage Patients',
    'session_queue': 'Session Queue',
    'sessions_count': 'sessions',
    'zero_sessions_logged': 'Zero Sessions Logged',
    'live_clinical_portals': 'Live Clinical Portals',
    'no_portals_active': 'No other portals active',
    'mobile_remote_access': 'Mobile & Remote Access',
    'clinic_wifi': 'Clinic Wi-Fi',
    'local_network_access': 'Local Network Access',
    'must_be_on_wifi': 'Must be on clinic Wi-Fi',
    'tailscale_vpn': 'Tailscale VPN',
    'secure_remote_access': 'Secure Remote Access',
    'works_anywhere': 'Works anywhere in the world',
    'core_utilities': 'Core Utilities',
    'local_db': 'Local DB',
    'backup': 'Backup',
    'stable': 'STABLE',
    'insight': 'Insight',
    'insight_quote': '"Precision monitoring is the foundation of superior treatment outcomes."',
    'sync_cloud': 'Sync Cloud',
    'syncing': 'Syncing...',
    'no_assessments_found': 'No matching assessments found',
    'verified': 'Verified',
    'no_notes': 'No clinical observations provided.',
    'username': 'Username',
    'password': 'Password',
    'secure_sign_in': 'Secure Sign In',
    'clinical_identifier': 'Clinical identifier',
    'create_new_account': 'Create new account',
    'authenticating': 'Authenticating...',
    'intel_suite': 'Clinical Intelligence Suite',
    'protected_encryption': 'Protected by Enterprise-Grade Encryption',
    'create_acc_requests': 'Create Account Requests',
    'next_step': 'Next Step',
    'back': 'Back',
    'choose_branch': 'Choose Clinic Branch',
    'choose_role': 'Choose Account Role',
    'doctor_account': 'Doctor Account',
    'staff_account': 'Staff Account',
    'acc_username': 'Account Username',
    'confirm_pwd': 'Confirm Password',
    'submit_request': 'Submit Request',
    'registering': 'Registering...',
    'req_submitted': 'Request Submitted Successfully',
    'req_submitted_desc': 'Your registration request has been forwarded to the clinic administrator for approval.',
    'select_branch': 'Select Branch',

    // Patients Directory (ClientsView)
    'patient_directory': 'Patient Directory',
    'manage_patient_records': 'Manage patient records and clinical history.',
    'cancel': 'Cancel',
    'add_patient': 'Add Patient',
    'new_patient_enrollment': 'New Patient Enrollment',
    'first_name': 'First Name',
    'last_name': 'Last Name',
    'phone_number': 'Phone Number',
    'age': 'Age',
    'address': 'Address',
    'how_did_you_know_us': 'How did you know us?',
    'primary_clinical_notes': 'Primary Clinical Notes',
    'profile_type': 'Profile Type',
    'physical_therapy': 'Physical Therapy',
    'nutrition': 'Nutrition',
    'lymphatic': 'Lymphatic',
    'register_patient_profile': 'Register Patient Profile',
    'all_patients': 'All Patients',
    'search_directory': 'Search directory...',
    'sort': 'Sort:',
    'newest_first': 'Newest First',
    'oldest_first': 'Oldest First',
    'active': 'Active',
    'archived': 'Archived',
    'no_results_matched': 'No results matched',
    'directory_empty': 'The directory is currently empty.',
    'patient_details': 'Patient Details',
    'contact_info': 'Contact Information',
    'reference_id': 'Reference ID',
    'primary_contact': 'Primary Contact',
    'toast_patient_created': 'Patient record created successfully!',
    'toast_patient_error': 'Error creating patient: ',
    'search_results_empty': 'We couldn\'t find any patients matching "{searchTerm}".',

    // Calendar View
    'clinical_schedule': 'Clinical Schedule',
    'manage_appointments': 'Manage appointments and availability',
    'search_schedule': 'Search schedule...',
    'new_session': 'New Session',
    'edit_session': 'Edit Session',
    'no_sessions': 'No sessions',
    'mark_session_completed': 'Mark Session as Completed',
    'treatment_notes_optional': 'Treatment Notes (optional)',
    'progress_notes_optional': 'Progress Notes (optional)',
    'confirm_complete': 'Confirm Complete',
    'desc_today_treatment': 'Describe today\'s treatment...',
    'patient_progress_obs': 'Patient progress observations...',
    'toast_select_patient': 'Please select a patient.',
    'toast_select_doctor': 'Please select a doctor.',
    'toast_apt_saved': 'Appointment successfully saved!',
    'toast_sys_error': 'System Error: ',
    'conflict_doctor_assign': 'Notice: Dr. {name} already has a session at this hour. Assign anyway?',
    'conflict_capacity_reached': 'Notice: There are already {count} sessions scheduled at this hour. Assign anyway?',
    'delete_apt_confirm': 'Delete this appointment permanently?',
    'avail_check_notice': 'System will automatically check for availability. Notices will trigger for conflicts.',
    'select_patient_prompt': 'Select Patient...',
    'select_doctor_prompt': 'Select Doctor...',
    'search_doctor': 'Search doctor...',
    'search_patient': 'Search patient...',
    'no_patients_found': 'No patients found',
    'no_doctors_found': 'No doctors found',
    'date_time': 'Date & Time',
    'status': 'Status',
    'select_session_type': 'Select Session Type...',
    'other': 'Other',
    'update': 'Update',
    'confirm': 'Confirm',
    'unassigned': 'Unassigned',
    'click_to_schedule': '＋ Click to schedule at {time}',

    // Reports View
    'clinic_audit_report': 'Clinic Audit Report',
    'flat_spreadsheet_view': 'Flat spreadsheet view of sessions, billing, loans and wastes.',
    'print_sheet': 'Print Sheet',
    'evolve_clinical_suite': 'REVIVE Clinical Management Suite',
    'daily_practice_report': 'DAILY PRACTICE REPORT',
    'weekly_practice_report': 'WEEKLY PRACTICE REPORT',
    'bi_weekly_practice_report': 'BI-WEEKLY PRACTICE REPORT',
    'tri_weekly_practice_report': 'TRI-WEEKLY PRACTICE REPORT',
    'custom_range_report': 'CUSTOM RANGE REPORT',
    'monthly_practice_report': 'MONTHLY PRACTICE REPORT',
    'period': 'Period:',
    'doctor_label': 'Doctor:',
    'generated_label': 'Generated:',
    'patients_treated': 'Patients Treated',
    'sessions_logged': 'Sessions Logged',
    'revenue_realized': 'Revenue Realized',
    'net_revenue': 'Net Revenue',
    'treatment_sessions_sheet': '1. Clinical Treatment & Sessions Sheet',
    'time_date': 'Time / Date',
    'patient_name': 'Patient Name',
    'session_no': 'Session No.',
    'treatment_rehab_protocols': 'Treatment & Rehabilitation Protocols',
    'progress_observations': 'Progress Observations',
    'no_rehab_sessions_logged': 'No clinical rehabilitation sessions logged during this period.',
    'realized_revenue_sheet': '2. Realized Revenue & Receipts Sheet',
    'payment_type': 'Payment Type',
    'acquisition_details': 'Acquisition Details',
    'net_paid': 'Net Paid',
    'prepaid_package': 'Prepaid Package ({count} Sessions Block)',
    'per_session_treatment': 'Per-session Clinical Treatment',
    'no_billing_receipts': 'No billing receipts or payments recorded during this period.',
    'staff_doctor_loans': '3. Staff & Doctor Loans Sheet',
    'role': 'Role',
    'note': 'Note',
    'settled': 'Settled',
    'no_loans_recorded': 'No loans recorded during this period.',
    'total_loans': 'Total Loans',
    'clinic_wastes_sheet': '4. Clinic Wastes & Consumables Sheet',
    'item': 'Item',
    'qty': 'Qty',
    'unit_cost': 'Unit Cost',
    'total': 'Total',
    'no_waste_items': 'No waste items recorded during this period.',
    'total_wastes': 'Total Wastes',
    'shift_attendance_log': '5. Shift Attendance & Check-In Log Sheet',
    'classification': 'Classification',
    'check_in': 'Check-In',
    'check_out': 'Check-Out',
    'hours_worked': 'Hours Worked',
    'no_attendance_logs': 'No shift attendance logs recorded during this period.',
    'daily_consolidated_log': '6. Daily Log Consolidated Sheet',
    'patient_volume': 'Patient Volume',
    'aggregate_revenue': 'Aggregate Revenue',
    'biometric_system_isolated': 'Biometric System Isolated Pass Verification',
    'summary_extracted_local': 'This summary is extracted from local encrypted database records. Privacy and compliance checks: PASS.',
    'authorized_physiotherapist': 'Authorized by generating physical therapist.',
    'practitioner_clinician_signature': 'Practitioner Clinician Signature',
    'verification_stamp_log': 'Verification Stamp Log',
    'day_opt': 'Day',
    'week_opt': 'Week',
    '2weeks_opt': '2 Weeks',
    '3weeks_opt': '3 Weeks',
    'month_opt': 'Month',
    'custom_range_opt': 'Custom Range',
    'select_month_opt': 'Select Month',
    'all_doctors': 'All Doctors',
    'to_date_connector': 'to',

    // Finance Management View
    'payroll_tab': 'Payroll',
    'loans_tab': 'Loans',
    'wastes_tab': 'Wastes',
    'daily_tab': 'Daily',
    'services_tab': 'Services',
    'financial_operations': 'Financial Operations',
    'financial_operations_desc': 'Manage practitioner payroll, staff loans, waste records, and service pricing structures.',
    'monthly_revenue_indicator': 'Monthly Realized Revenue',
    'staff_payroll_ledger': 'Staff & Doctor Payroll Ledger',
    'search_practitioners': 'Search practitioners...',
    'practitioner_details': 'Practitioner Details',
    'base_salary': 'Base Salary (EGP)',
    'dynamic_commission': 'Dynamic Commission',
    'calculated_payout': 'Calculated Payout',
    'ledger_actions': 'Ledger Actions',
    'calculate_salary': 'Calculate Salary',
    'salary_saved': 'Saved',
    'edit_payroll_calculations': 'Edit Payroll Calculations',
    'sessions_completed_in': 'Sessions completed in {month}',
    'pt_sessions': 'PT Sessions',
    'nutrition_sessions': 'Nutrition Sessions',
    'lymphatic_sessions': 'Lymphatic Sessions',
    'other_sessions': 'Other Sessions',
    'save_salary_record': 'Save Salary Record',
    'loans_advances_management': 'Loans & Advances Management',
    'issue_new_loan': 'Issue New Loan / Advance',
    'settle_all_loans': 'Settle All Loans',
    'remaining_deductions': 'Remaining Deductions',
    'loans_history_for': 'Loans history for {month}',
    'no_loans_found_period': 'No active or settled loans found for this period.',
    'wastes_expense_tracking': 'Wastes & Expense Tracking',
    'record_waste_purchase': 'Record Waste / Purchase',
    'daily_expense_logs': 'Daily Expense Logs',
    'total_expense': 'Total Expense',
    'no_expense_logged_day': 'No waste items or expenses logged for this day.',
    'service_pricing_library': 'Service Pricing & Library',
    'define_new_service': 'Define New Service',
    'service_cost': 'Cost (EGP)',
    'number_of_sessions': 'Number of Sessions',
    'actions': 'Actions',
    'edit': 'Edit',
    'delete': 'Delete',
    'edit_service': 'Edit Service',
    'update_service': 'Update Service',
    'confirm_delete_service': 'Permanently delete this service?',

    // Client Profile View
    'sync_local_database': 'Sync Local DB',
    'syncing_local': 'Syncing Local...',
    'print_patient_report': 'Print Report',
    'pt_profile_tab': 'PT Profile',
    'nutrition_profile_tab': 'Nutrition',
    'lymphatic_profile_tab': 'Lymphatic',
    'medical_records_tab': 'Medical Records',
    'home_exercises_tab': 'Home Exercises',
    'clinical_exercises_tab': 'Clinical Exercises',
    'session_finance_tab': 'Session Finance',
    'recovery_insights_tab': 'Recovery Insights',
    'edit_patient_profile': 'Edit Patient Profile',
    'save_changes_btn': 'Save Changes',
    'diagnosis_history_section': 'Diagnosis & History',
    'no_prior_medical_history': 'No prior medical history recorded for this patient.',
    'patient_access_pin_lbl': 'Patient Access PIN',
    'sync_portal_btn': 'Sync Portal',
    'synchronizing': 'Synchronizing...',
    'patient_clinical_profiles': 'Patient Clinical Profiles',
    'add_pt_profile': 'Add PT Profile',
    'add_nutrition_profile': 'Add Nutrition Profile',
    'add_lymphatic_profile': 'Add Lymphatic Profile',
    'activate_account': 'Activate',
    'archive_account': 'Archive',
    'purge_record_btn': 'Purge Record',
    'medical_documents_header': 'Medical Documents',
    'diagnostic_imagery_desc': 'Diagnostic imagery, reports, and digital records.',
    'import_record_btn': 'Import Record',
    'no_digital_records_found': 'No digital records found',
    'securely_store_pdfs': 'Securely store PDFs, diagnostic results, or clinical scans.',
    'open_document_tooltip': 'Open Document',
    'reveal_in_system_tooltip': 'Reveal in System',
    'record_payment_btn': 'Record Payment',
    'active_package_status': 'Active Session Package Status',
    'realtime_sync_timeline': 'Real-Time Sync with Treatment Timeline',
    'total_purchased': 'Total Purchased',
    'sessions_used': 'Sessions Used',
    'sessions_left': 'Sessions Left',
    'service_classification': 'Service Classification',
    'select_service_type': 'Select Service Type...',
    'session_count_label': 'Session Count',
    'total_transaction_value': 'Total Transaction Value ($)',
    'fixed_rate_sync_notice': '* Fixed rate synchronized with Session Type Library.',
    'authenticate_record': 'Authenticate & Record Transaction',
    'no_financial_records': 'No financial records detected.',
    'transaction_date': 'Transaction Date',
    'service_details': 'Service Details',
    'volume_notes': 'Volume / Notes',
    'net_amount': 'Net Amount',
    'payment_notes_placeholder': 'Payment Notes...',
    'sessions_unit': 'Sessions',
    'patient_access_portal': 'Patient Access',
    'scan_code_portal': 'Scan this code with the patient\'s phone to open their recovery portal.',
    'done_btn': 'Done',
    'active_profile_confirm_delete': 'Are you sure you want to permanently delete the {type} Profile? This will delete all Red Flags, Subjective, Objective, and measurements data related to this profile.',
    'purge_client_confirm': 'CRITICAL WARNING: Permanently delete {name}? This action is irreversible.',
    'initial_setup': 'INITIAL SETUP',
    'init_admin_acc': 'Initialize Administrator Account',
    'new_password': 'New Password',
    'complete_secure_setup': 'Complete Secure Setup',
    'initializing': 'Initializing...',
    'sys_config_mode_footer': 'System Configuration Mode | &copy; 2026 Revive Medical',
    'pwd_mismatch_error': 'Passwords do not match. Please verify.',
    'pwd_length_error': 'Security requirement: Password must be at least 6 characters.',
    'setup_failed_error': 'Setup initialization failed.',
    'critical_setup_error': 'A critical system error occurred during initial setup.',
    'welcome_branch': 'Welcome, {name}. Choose a branch to manage.',
    'no_branches_found': 'No branches found. Please contact your administrator.',
    'branch_active_lbl': 'Branch #{id} · Active',
    'branch_select_footer': 'Each branch operates with fully isolated data. Your selection sets the active branch for this session.',
    'version_multibranch_footer': 'Version 4.0.0-REVIVE · Multi-Branch Edition',
    'active_loans': 'Active Loans',
    'reset_month': 'Reset Month',
    'no_staff_doctors_found': 'No staff or doctors found.',
    'total_loaned': 'Total Loaned',
    'add_loan': 'Add Loan',
    'amount': 'Amount',
    'note_optional': 'Note (optional)',
    'reason_loan_placeholder': 'Reason for loan...',
    'save': 'Save',
    'mark_settled_tooltip': 'Mark as settled',
    'delete_perm_tooltip': 'Delete permanently',
    'no_active_loans_period': 'No active loans for this period.',
    'no_loans_found': 'No loans found.',
    'days_with_waste': 'Days with waste entries',
    'daily_total': 'Daily Total',
    'add_item': 'Add Item',
    'item_name': 'Item Name',
    'quantity': 'Quantity',
    'unit_cost_egp': 'Unit Cost (EGP)',
    'item_name_placeholder': 'e.g. Gloves, Tea, Glasses...',
    'item_header': 'Item',
    'qty_header': 'Qty',
    'unit_cost_header': 'Unit Cost',
    'total_header': 'Total',
    'day_total': 'Day Total',
    'no_waste_recorded_day': 'No waste items recorded for this day.',
    'click_add_item_desc': 'Click "Add Item" to log clinic consumables.',
    'gross_revenue': 'Gross Revenue',
    'loans': 'Loans',
    'wastes': 'Wastes',
    'net_revenue_lbl': 'Net Revenue',
    'from_payments': 'FROM PAYMENTS',
    'record_singular': 'RECORD',
    'records_plural': 'RECORDS',
    'item_singular': 'ITEM',
    'items_plural': 'ITEMS',
    'net_gain': 'NET GAIN',
    'net_loss': 'NET LOSS',
    'revenue_breakdown': 'Revenue Breakdown',
    'loans_issued': 'Loans Issued',
    'clinic_wastes': 'Clinic Wastes',
    'net_clear_revenue': 'Net Clear Revenue',
    'loans_on_day': 'Loans on This Day',
    'waste_items_on_day': 'Waste Items on This Day',
    'no_financial_activity_day': 'No financial activity recorded for this day.',
    'session_type_library': 'Session Type Library',
    'manage_session_types_desc': 'Manage session types with fixed pricing used across all patient profiles.',
    'add_new_session_type': 'Add New Session Type',
    'name': 'Name',
    'sessions_package_optional': 'Sessions in Package (optional)',
    'leave_blank_single': 'Leave blank for single',
    'add_session_type_btn': 'Add Session Type',
    'no_session_types_defined': 'No session types defined yet.',
    'add_session_types_above_desc': 'Add session types above to use them in patient finance records.',
    'egp_per_session': 'EGP per session',
    'sessions_in_package_desc': 'sessions in package',
    'single_session': 'Single session',
    'all_filter': 'All',
    'active_filter': 'Active',
    'settled_filter': 'Settled',
    'ai_clinical_assistant': 'AI Clinical Assistant',
    'ai_subtitle': 'Evidence-based clinical decision support and treatment planning.',
    'patient_context_optional': 'Patient Context (Optional)',
    'general_query_no_context': 'General Query (No patient context)',
    'clinical_dilemma_question': 'Clinical Dilemma or Treatment Question',
    'ai_textarea_placeholder': 'e.g., Analyze the clinical history and suggest a multi-phase rehabilitation strategy for this patient\'s chronic condition...',
    'data_remains_encrypted_local': 'Data remains encrypted and local',
    'consult_assistant': 'Consult Assistant',
    'generating_analysis': 'Generating Analysis...',
    'system_error': 'System Error',
    'clinical_synthesis': 'Clinical Synthesis',
    'ai_processed': 'AI PROCESSED',
    'synthesis_failed': 'Synthesis Failed',
    'copy_to_clinical_notes': 'Copy to Clinical Notes',
    'ai_error_unexpected': 'An unexpected error occurred during AI synthesis.',
    'credentials_approvals': 'Credentials & Approvals',
    'credentials_approvals_desc': 'Review and authorize access requests for clinical staff and doctors',
    'refresh_requests': 'Refresh Requests',
    'search_account_requests_placeholder': 'Search by Username, Doctor Name, Role, or Branch...',
    'all_requests_filter': 'All Requests',
    'no_requests_found': 'No Requests Found',
    'no_requests_found_desc': 'There are no registration requests matching your current filters. New signups will appear here automatically.',
    'branch_header': 'Branch',
    'role_header': 'Role',
    'name_header': 'Name',
    'username_header': 'Username',
    'date_header': 'Date',
    'status_header': 'Status',
    'actions_header': 'Actions',
    'approve_btn': 'Approve',
    'deny_btn': 'Deny',
    'processed_status': 'Processed',
    'toast_failed_load_requests': 'Failed to load registration requests.',
    'toast_request_approved': 'Account "{username}" approved successfully!',
    'toast_request_approved_error': 'Error approving account: {error}',
    'toast_request_denied': 'Account request for "{username}" denied.',
    'toast_request_denied_error': 'Error denying request: {error}',
    'confirm_approve_request': 'Are you sure you want to approve the account for "{username}"?',
    'confirm_deny_request': 'Are you sure you want to deny the account request for "{username}"?',
    'shift_attendance_console': 'Shift Attendance Console',
    'shift_attendance_desc': 'Register arrival and departure times for clinic staff and doctors.',
    'toast_failed_load_attendance': 'Failed to load attendance logs',
    'toast_clock_in_success': 'Clocked In {username} at {time} successfully!',
    'toast_clock_in_failed': 'Failed to clock in {username}',
    'toast_clock_out_success': 'Clocked Out {username} at {time} successfully!',
    'toast_clock_out_failed': 'Failed to clock out {username}',
    'toast_sys_error_occurred': 'System error occurred',
    'time_station': 'Time Station',
    'welcome_username': 'Welcome, {username}!',
    'role_label': 'Role:',
    'clock_in_btn': 'Clock In (Arrival)',
    'clock_out_btn': 'Clock Out (Departure)',
    'checked_in_at': 'Checked In at {time}',
    'checked_out_at': 'Checked Out at {time}',
    'shift_logs_attendance': 'Shift Logs & Attendance',
    'viewing_shift_history': 'Viewing shift history for chosen clinical date.',
    'search_staff_role_placeholder': 'Search staff or role...',
    'select_date_lbl': 'Select Date:',
    'syncing_shift_history': 'Syncing Shift History...',
    'no_clinical_users_registered': 'No clinical users registered in system.',
    'classification_header': 'Classification',
    'arrival_header': 'Arrival (Clock In)',
    'departure_header': 'Departure (Clock Out)',
    'daily_status_header': 'Daily Status',
    'you_tag': 'You',
    'check_in_btn': 'Check In',
    'check_out_btn': 'Check Out',
    'completed_status': 'Completed',
    'on_duty_status': 'On Duty',
    'absent_pending_status': 'Absent / Pending',
    // User Management
    'users_tab_lbl': 'Users',
    'doctors_tab_lbl': 'Doctors',
    'clinic_team_mgmt_title': 'Clinic Team Management',
    'clinic_team_mgmt_desc': 'Manage your staff accounts and access controls. You can add new team members or update security credentials for existing ones.',
    'add_team_member_btn': 'Add Team Member',
    'search_by_username_placeholder': 'Search by username...',
    'active_branch_lbl': 'Active Branch:',
    'register_security_creds': 'Register Security Credentials',
    'access_privilege_role': 'Access Privilege Role',
    'role_owner': 'Owner (Super Admin)',
    'role_admin': 'Administrator (Full Access)',
    'role_cfo': 'Chief Financial Officer (CFO)',
    'role_staff': 'Clinical Staff (Daily Operations)',
    'role_doctor': 'Medical Specialist / Doctor',
    'assign_doctor_profile': 'Assign Doctor Profile',
    'select_doctor_profile_prompt': 'Select Doctor Profile...',
    'assigned_branches_ctrl': 'Assigned Branches (Control Privileges)',
    'default_operating_branch': 'Default Operating Branch',
    'security_pwd': 'Security Password',
    'auth_register_account': 'Authenticate & Register Account',
    'active_accounts_section': 'Active Accounts',
    'staff_member_username_hdr': 'Staff Member / Username',
    'access_role_hdr': 'Access Role',
    'all_branches_owner': 'All Branches (Owner)',
    'no_branches_assigned': 'No branches assigned',
    'status_active': 'active',
    'status_frozen': 'frozen',
    'assign_branches_tooltip': 'Assign Branches',
    'reset_creds_tooltip': 'Reset Credentials',
    'revoke_access_tooltip': 'Revoke Access',
    'frozen_accounts_section': 'Frozen Accounts',
    'doctor_mgmt_title': 'Doctor Management',
    'doctor_mgmt_desc': 'Configure active practitioners and specialists. Frozen doctors will be excluded from signature options.',
    'add_doctor_btn': 'Add Doctor',
    'search_doctors_placeholder': 'Search doctors by name or specialty...',
    'modify_doctor_profile': 'Modify Doctor Profile:',
    'add_new_doctor_profile': 'Add New Doctor Profile',
    'doctor_name_lbl': 'Doctor Name',
    'specialty_lbl': 'Specialty',
    'profile_status_lbl': 'Profile Status',
    'update_doctor_profile': 'Update Doctor Profile',
    'register_doctor_profile': 'Register Doctor Profile',
    'credential_reset_title': 'Credential Reset',
    'reissuing_access_for': 'Re-issuing access for',
    'new_secure_pwd': 'New Secure Password',
    'update_creds_btn': 'Update Credentials',
    'config_branch_access_for': 'Configure branch access for',
    'select_branches_lbl': 'Select Branches',
    // BioMetrics / AssessmentTab
    'full_body_scanning_protocol': 'Full Body Scanning Protocol',
    'report_auto_gen': 'Report Auto-Gen',
    'report_disabled': 'Report Disabled',
    'export_report': 'Export Report',
    'findings_lbl': 'Findings:',
    'search_body_region_placeholder': 'Search by Body Region (e.g. Shoulder, Knee, Back)...',
    'assessment_suffix': 'Assessment',
    'positive_finding_title': 'Positive Finding',
    'positive_finding_btn': 'Positive',
    'negative_cleared_title': 'Negative / Cleared',
    'negative_cleared_btn': 'Negative',
    'clinical_positive_findings_hdr': 'Clinical Positive Findings',
    'biometric_assessment_report_sub': 'Bio-Metric Assessment Report',
    'confirmed_finding_tag': 'Confirmed Finding',
    'end_clinical_protocol_footer': 'End of clinical assessment protocol — Secure Sync Active',
    'bulk_data_mgmt': 'Bulk Data Management',
    'bulk_data_mgmt_desc': 'Import or export the full assessment library via Excel',
    'column_guide_btn': 'Column Guide',
    'export_excel_btn': 'Export Excel',
    'import_excel_btn': 'Import Excel',
    'req_excel_cols': 'Required Excel Column Names',
    'add_new_clinical_region': 'Add New Clinical Region',
    'initialize_region_btn': 'Initialize Region',
    'remove_region_btn': 'Remove Region',
    'rename_region_tooltip': 'Rename Region',
    'register_new_test_protocol': 'Register New Test Protocol',
    'link_test_btn': 'Link Test',
    'syncing_biometrics': 'Syncing Bio-Metric Data...',
    'protocol_lbl': 'Protocol',
    'syncing_admin': 'Evolve Admin Sync...',
    'exporting_lbl': 'Exporting...',
    'importing_lbl': 'Importing...',
    'required_lbl': 'Required',
    'col_guide_region_desc': 'Assessment region name (e.g. "Shoulder"). Auto-created if not exists.',
    'col_guide_name_desc': 'Clinical test name (e.g. "Apprehension Test").',
    'col_guide_desc_desc': 'Optional short description of the test protocol.',
    'add_region_placeholder': 'e.g., Cervical Spine, Hip, Ankle...',
    'confirm_delete_region': 'Delete this region and ALL associated tests/results?',
    'confirm_delete_test': 'Delete this clinical test?',
    'test_name_placeholder': 'Test Name',
    'test_desc_placeholder': 'Short Description',
    'test_name_eg_placeholder': 'Test Name (e.g., Apprehension Test)',
    'test_desc_optional_placeholder': 'Short Description (optional)',
    'import_success_msg': '✓ Imported {imported} tests ({skipped} skipped).',
    'import_failed_msg': '✗ Import failed: {error}',
    'export_success_msg': '✓ Exported to {fileName}',
    'export_failed_msg': '✗ Export failed: {error}',
    'shoulder': 'Shoulder',
    'arm (biceps/triceps)': 'Arm (Biceps/Triceps)',
    'upper back': 'Upper Back',
    'mid back': 'Mid Back',
    'lower back': 'Lower Back',
    'leg: anterior thigh': 'Leg: Anterior Thigh',
    'leg: posterior thigh': 'Leg: Posterior Thigh',
    'leg: knee': 'Leg: Knee',
    'leg: calf': 'Leg: Calf',
    'cervical spine': 'Cervical Spine',
    'hip': 'Hip',
    'ankle': 'Ankle',
    'hawkins-kennedy test': 'Hawkins-Kennedy Test',
    'neer test': 'Neer Test',
    'empty can test': 'Empty Can Test',
    "speed's test": "Speed's Test",
    "yergason's test": "Yergason's Test",
    "spurling's test": "Spurling's Test",
    'slump test': 'Slump Test',
    'straight leg raise': 'Straight Leg Raise',
    'faber test': 'Faber Test',
    'thomas test': 'Thomas Test',
    'popliteal angle test': 'Popliteal Angle Test',
    'lachman test': 'Lachman Test',
    'mcmurray test': 'McMurray Test',
    'valgus stress test': 'Valgus Stress Test',
    'thompson test': 'Thompson Test',
    "homan's sign": "Homan's Sign",
    'doctor_signature_req_error': 'Doctor signature is required.',
    'red_flags_saved': 'Red flags saved.',
    'save_failed': 'Save failed.',
    'subjective_updated': 'Subjective updated.',
    'new_assessment_saved': 'New physical assessment subjective saved.',
    'objective_saved': 'Objective data saved.',
    'assessment_deleted': 'Assessment deleted.',
    'failed_to_delete': 'Failed to delete.',
    'by_clinician': 'By:',
    'confirm_delete_assessment': 'Are you sure you want to delete this physical assessment?',
    'confirm_delete_session_plan': 'Are you sure you want to delete this session plan?',
    'session_plan_deleted': 'Session plan deleted.',
    'session_plan_updated': 'Session plan updated.',
    'new_session_plan_saved': 'New session plan saved.',
    'cloned_from_latest_success': 'Cloned from latest session plan.',
    'joint_name_placeholder_eg': 'e.g. Knee',
    'angle_placeholder_eg': 'e.g. 120°',
    'session_item_notes_placeholder': '{itemName} notes...',
    'could_not_init_draft': 'Could not initialize assessment draft.',
    'session_history_lbl': 'Sessions History',
    // PhysicalTherapyProfile
    'red_flags_tab': 'Red Flags',
    'physical_assessment_tab': 'Physical Assessment',
    'special_tests_tab': 'Special Tests',
    'session_plan_tab': 'Session Plan',
    'neuro_red_flags_screening': 'Neurological Red Flags Screening',
    'neuro_red_flags_desc': 'Select all applicable neurological red flags. Selecting No clears all others.',
    'other_describe_lbl': 'Other — Describe',
    'describe_other_red_flag_placeholder': 'Describe the other red flag...',
    'doctor_signature_req': 'Doctor Signature (Required)',
    'select_assigning_clinician': 'Select Assigning Clinician...',
    'saving_lbl': 'Saving...',
    'subjective_assessment_title': 'Subjective Assessment',
    'chief_complaint_lbl': 'Chief Complaint',
    'enter_chief_complaint_placeholder': 'Enter chief complaint...',
    'aggravating_factors_lbl': 'Aggravating Factors',
    'enter_aggravating_placeholder': 'Enter aggravating factors...',
    'easing_factors_lbl': 'Easing Factors',
    'enter_easing_placeholder': 'Enter easing factors...',
    'pain_scale_vas': 'Pain Scale (VAS 0-10)',
    'no_pain_0': 'No Pain (0)',
    'moderate_5': 'Moderate (5)',
    'worst_pain_10': 'Worst Pain (10)',
    'irritability_lbl': 'Irritability',
    'irritability_notes_placeholder': 'Irritability notes...',
    'nature_lbl': 'Nature',
    'nature_notes_placeholder': 'Nature notes...',
    'objective_assessment_title': 'Objective Assessment',
    'range_of_motion_title': 'Range of Motion',
    'add_joint_btn': 'Add Joint',
    'no_joint_assessments': 'No joint assessments added',
    'joint_tbl_hdr': 'Joint',
    'pain_tbl_hdr': 'Pain',
    'limitation_tbl_hdr': 'Limitation',
    'angle_tbl_hdr': 'Angle',
    'positive_special_tests_lbl': 'Positive Special Tests (from Special Tests tab)',
    'no_positive_findings_recorded': 'No positive findings recorded.',
    'palpation_notes_lbl': 'Palpation Notes',
    'palpation_findings_placeholder': 'Palpation findings...',
    'assessments_history_title': 'Assessments History',
    'new_btn': 'New',
    'no_assessments_recorded': 'No assessments recorded yet.',
    'draft_status': 'Draft',
    'unsigned_lbl': 'Unsigned',
    'editing_physical_assessment': 'Editing Physical Assessment',
    'new_physical_assessment': 'New Physical Assessment',
    'saved_on_lbl': 'Saved on',
    'fill_subjective_first': 'Fill out the subjective assessment first',
    'clinical_assessment_library': 'Clinical Assessment Library',
    'search_region_test_placeholder': 'Search region or test name...',
    'no_regions_found_lbl': 'No regions found',
    'session_plan_title': 'Session Plan',
    'editing_session_plan': 'Editing Session Plan',
    'new_session_plan': 'New Session Plan',
    'modify_session_plan_desc': 'Modify details for this previously recorded session.',
    'new_session_plan_desc': 'Select treatments and options to document this clinical session.',
    'clone_from_latest_btn': 'Clone From Latest',
    'selected_unit': 'selected',
    'specify_other_treatment_placeholder': 'Specify other treatment...',
    'red_flag_myelopathy': 'Myelopathy',
    'red_flag_cauda_equina': 'Cauda Equina',
    'red_flag_drop_foot': 'Drop Foot',
    'red_flag_urinary_incontinence': 'Urinary Incontinence',
    'red_flag_motor_weakness': 'Motor Weakness',
    'red_flag_other': 'Other',
    'red_flag_no': 'No',
    'irritability_high': 'High',
    'irritability_mod': 'Mod',
    'irritability_low': 'Low',
    'nature_inflammatory': 'Inflammatory',
    'nature_mechanical': 'Mechanical',
    'nature_neural': 'Neural',
    'session_plan_sec_electrotherapy': 'Electrotherapy',
    'session_plan_sec_manual_therapy': 'Manual Therapy',
    'session_plan_sec_tools': 'Tools',
    'session_plan_item_tens': 'TENS',
    'session_plan_item_nmes': 'NMES',
    'session_plan_item_hot_pack': 'Hot Pack',
    'session_plan_item_laser': 'Laser',
    'session_plan_item_mobilisation': 'Mobilisation',
    'session_plan_item_mobilisation_with_movement': 'Mobilisation with Movement',
    'session_plan_item_manipulation': 'Manipulation',
    'session_plan_item_manual_soft_tissue_release': 'Manual Soft Tissue Release',
    'session_plan_item_dry_needle': 'Dry Needle',
    'session_plan_item_dry_cupping': 'Dry Cupping',
    'session_plan_item_kinesio_taping': 'Kinesio Taping',
    'session_plan_item_rigid_tape': 'Rigid Tape',
    'session_plan_item_blade_iastm': 'Blade/IASTM',
    'session_plan_item_bfr': 'BFR',
    'session_plan_item_other': 'Other',
  },
  ar: {
    // Sidebar & Navigation
    'revive_clinic': 'عيادة ريفايف',
    'dashboard': 'لوحة التحكم',
    'recovery_monitoring': 'مراقبة التعافي',
    'calendar': 'التقويم',
    'patients': 'المرضى',
    'reports': 'التقارير',
    'finance': 'المالية',
    'clinic_assessment': 'التقييم السريري',
    'exercise_library': 'مكتبة التمارين',
    'investigation_library': 'مكتبة الفحوصات',
    'ai_assist': 'مساعد ريفايف الذكي',
    'account_requests': 'طلبات الحسابات',
    'shift_attendance': 'حضور نوبات العمل',
    'settings_backup': 'الإعدادات والنسخ الاحتياطي',
    'logout': 'تسجيل الخروج',
    'version': 'الإصدار',
    'user': 'المستخدم',
    'branch': 'الفرع',
    'switch_branch': 'تبديل الفرع',
    'home': 'الرئيسية',
    'schedule': 'الجدول',
    'menu': 'القائمة',

    // Settings
    'system_settings': 'إعدادات النظام',
    'settings_subtitle': 'تهيئة البروتوكولات السريرية، وحسابات المستخدمين، والخدمات اللوجستية للنظام.',
    'db_backup': 'قاعدة البيانات والنسخ الاحتياطي',
    'whatsapp_templates': 'قوالب الواتساب',
    'team_management': 'إدارة الفريق',
    'branches': 'الفروع',
    'data_persistence': 'حفظ البيانات والاستمرارية',
    'db_backup_desc': 'إنشاء تصدير مشفر بالكامل لقاعدة بيانات SQLite المحلية. يتضمن ذلك جميع سجلات المرضى والتاريخ السريري وتكوينات النظام.',
    'export_backup': 'تصدير نسخة احتياطية محلية',
    'network_db': 'قاعدة بيانات الشبكة المشتركة',
    'network_db_desc': 'قم بتهيئة مسار قاعدة بيانات مشترك عبر شبكتك المحلية. يتيح ذلك لمحطات عمل متعددة الوصول إلى نفس البيانات وتحديثها بشكل متزامن.',
    'active_db_loc': 'موقع قاعدة البيانات النشطة:',
    'select_shared_db': 'اختر قاعدة البيانات المشتركة',
    'financial_period': 'الفترة المالية',
    'financial_period_desc': 'إعادة تعيين تتبع الإيرادات في لوحة التحكم لبدء فترة مالية أو شهر جديد. تظل سجلات المرضى والبيانات السريرية دون تغيير.',
    'reset_period': 'إعادة تعيين فترة التحليل',
    'whatsapp_reminder': 'قالب تذكير الموعد (واتساب)',
    'whatsapp_reminder_desc': 'تخصيص نص الرسالة التلقائية المرسلة للمرضى لتأكيد موعدهم',
    'whatsapp_review': 'قالب مراجعة الجلسة (واتساب)',
    'whatsapp_review_desc': 'تخصيص نص الرسالة التلقائية المرسلة للمرضى بعد اكتمال الجلسة العلاجية',
    'template_text': 'نص قالب الرسالة',
    'dynamic_tokens': 'العلامات المرجعية الديناميكية:',
    'dynamic_tokens_desc': 'استخدم هذه العلامات لملء بيانات الموعد تلقائياً في نص الرسالة:',
    'save_templates': 'حفظ القوالب',
    'loading_path': 'جاري تحميل المسار...',

    // Dashboard
    'today_appts': 'مواعيد اليوم',
    'total_patients': 'إجمالي المرضى',
    'active_staff': 'الموظفون النشطون',
    'revenue': 'الإيرادات',
    'active_sessions': 'الأجهزة المتصلة نشطة',
    'diagnostic_tests': 'الفحوصات التشخيصية',
    'high_pain_alerts': 'تنبيهات الألم الشديد',
    'search_patients': 'البحث عن المرضى...',
    'loading_branch': 'جاري تحميل بيانات الفرع...',
    'switch_branch_btn': 'تبديل الفرع',
    'clinical_dashboard': 'لوحة التحكم السريرية',
    'dashboard_subtitle': 'مراقبة المرضى في الوقت الفعلي ومقاييس الممارسة.',
    'recovery_monitoring_subtitle': 'تقييمات ألم المرضى السريرية في الوقت الفعلي.',
    'session': 'الجلسة الحالية',
    'all_time': 'كل الوقت',
    'critical_pain_alerts': 'تنبيهات الألم الحرجة',
    'urgent_attention': 'اهتمام عاجل',
    'daily_queue': 'الطابور اليومي',
    'scheduled': 'مجدول',
    'active_load': 'الحمل النشط',
    'in_system': 'في النظام',
    'performance': 'الأداء المالي',
    'elite_management': 'إدارة سريرية متميزة',
    'elite_management_desc': 'مزامنة آمنة لقاعدة البيانات. التحليل السريري بالذكاء الاصطناعي. حلقة ردود فعل المرضى الآلية.',
    'manage_patients': 'إدارة المرضى',
    'session_queue': 'طابور الجلسات',
    'sessions_count': 'جلسة/جلسات',
    'zero_sessions_logged': 'لا توجد جلسات مسجلة',
    'live_clinical_portals': 'البوابات السريرية المباشرة',
    'no_portals_active': 'لا توجد بوابات نشطة أخرى',
    'mobile_remote_access': 'الوصول عن بعد والمحمول',
    'clinic_wifi': 'واي فاي العيادة',
    'local_network_access': 'الوصول إلى الشبكة المحلية',
    'must_be_on_wifi': 'يجب أن تكون متصلاً بشبكة واي فاي العيادة',
    'tailscale_vpn': 'شبكة VPN تيلسكيل',
    'secure_remote_access': 'الوصول الآمن عن بعد',
    'works_anywhere': 'يعمل في أي مكان في العالم',
    'core_utilities': 'الأدوات الأساسية',
    'local_db': 'قاعدة البيانات المحلية',
    'backup': 'نسخة احتياطية',
    'stable': 'مستقر',
    'insight': 'رؤية سريرية',
    'insight_quote': '"المراقبة الدقيقة هي أساس نتائج العلاج المتفوقة."',
    'sync_cloud': 'مزامنة السحاب',
    'syncing': 'جاري المزامنة...',
    'no_assessments_found': 'لم يتم العثور على تقييمات مطابقة',
    'verified': 'تم التحقق',
    'no_notes': 'لم يتم تقديم أي ملاحظات سريرية.',
    'username': 'اسم المستخدم',
    'password': 'كلمة المرور',
    'secure_sign_in': 'تسجيل دخول آمن',
    'clinical_identifier': 'المعرف السريري الخاص بك',
    'create_new_account': 'إنشاء حساب جديد',
    'authenticating': 'جاري التحقق والدخول...',
    'intel_suite': 'مجموعة الذكاء السريري المتكاملة',
    'protected_encryption': 'محمي بتشفير قوي من الفئة المؤسسية',
    'create_acc_requests': 'طلبات إنشاء الحسابات الجديد',
    'next_step': 'الخطوة التالية',
    'back': 'رجوع',
    'choose_branch': 'اختر فرع العيادة الخاص بك',
    'choose_role': 'اختر دور الحساب السريري',
    'doctor_account': 'حساب طبيب ممارس',
    'staff_account': 'حساب موظف إداري',
    'acc_username': 'اسم مستخدم الحساب',
    'confirm_pwd': 'تأكيد كلمة المرور',
    'submit_request': 'إرسال طلب التسجيل',
    'registering': 'جاري التسجيل وإرسال الطلب...',
    'req_submitted': 'تم إرسال الطلب بنجاح',
    'req_submitted_desc': 'تم إرسال طلب التسجيل الخاص بك إلى مدير النظام لاعتماده والموافقة عليه.',
    'select_branch': 'اختر الفرع',

    // Patients Directory (ClientsView)
    'patient_directory': 'دليل المرضى',
    'manage_patient_records': 'إدارة سجلات المرضى والتاريخ السريري للعيادة.',
    'cancel': 'إلغاء',
    'add_patient': 'إضافة مريض',
    'new_patient_enrollment': 'تسجيل مريض جديد في النظام',
    'first_name': 'الاسم الأول',
    'last_name': 'الاسم الأخير',
    'phone_number': 'رقم الهاتف',
    'age': 'العمر',
    'address': 'العنوان ورقم الشارع',
    'how_did_you_know_us': 'كيف عرفت العيادة؟',
    'primary_clinical_notes': 'الملاحظات السريرية الأولية / التشخيص',
    'profile_type': 'تصنيف الحالة',
    'physical_therapy': 'العلاج الطبيعي',
    'nutrition': 'التغذية العلاجية',
    'lymphatic': 'التصريف الليمفاوي',
    'register_patient_profile': 'حفظ وتسجيل المريض',
    'all_patients': 'جميع المرضى',
    'search_directory': 'البحث في الدليل...',
    'sort': 'ترتيب:',
    'newest_first': 'الأحدث أولاً',
    'oldest_first': 'الأقدم أولاً',
    'active': 'نشط',
    'archived': 'مؤرشف',
    'no_results_matched': 'لم يتم العثور على أي نتائج مطابقة للبحث',
    'directory_empty': 'الدليل فارغ ولا توجد سجلات حالية.',
    'patient_details': 'بيانات المريض الأساسية',
    'contact_info': 'معلومات الاتصال',
    'reference_id': 'الرقم المرجعي',
    'primary_contact': 'رقم الهاتف الأساسي',
    'toast_patient_created': 'تم تسجيل ملف المريض بنجاح!',
    'toast_patient_error': 'حدث خطأ أثناء إضافة المريض: ',
    'search_results_empty': 'لم نتمكن من العثور على أي مريض يطابق "{searchTerm}".',

    // Calendar View
    'clinical_schedule': 'جدول المواعيد السريرية',
    'manage_appointments': 'تنظيم مواعيد المرضى والأجهزة والزيارات',
    'search_schedule': 'البحث في جدول المواعيد...',
    'new_session': 'حجز جلسة جديدة',
    'edit_session': 'تعديل بيانات الجلسة',
    'no_sessions': 'لا توجد جلسات مجدولة',
    'mark_session_completed': 'تسجيل إتمام الجلسة وإدخال الملاحظات',
    'treatment_notes_optional': 'تفاصيل العلاج (اختياري)',
    'progress_notes_optional': 'ملاحظات التحسن والتعافي (اختياري)',
    'confirm_complete': 'تأكيد وإتمام الجلسة',
    'desc_today_treatment': 'اكتب وصفاً للعلاج السريري المقدم اليوم...',
    'patient_progress_obs': 'ملاحظات حول استجابة وتحسن المريض...',
    'toast_select_patient': 'يرجى اختيار المريض أولاً.',
    'toast_select_doctor': 'يرجى اختيار الطبيب المعالج.',
    'toast_apt_saved': 'تم حفظ الموعد بنجاح!',
    'toast_sys_error': 'خطأ في النظام: ',
    'conflict_doctor_assign': 'تنبيه: الطبيب المعالج لديه جلسة أخرى في نفس هذا الوقت. هل تريد التأكيد على أي حال؟',
    'conflict_capacity_reached': 'تنبيه: هناك بالفعل {count} جلسات مسجلة في هذا التوقيت. هل تريد التأكيد على أي حال؟',
    'delete_apt_confirm': 'هل أنت متأكد من حذف هذا الموعد نهائياً؟',
    'avail_check_notice': 'يقوم النظام بالتحقق تلقائياً من توفر الغرف والأطباء لمنع حدوث تعارض في المواعيد.',
    'select_patient_prompt': 'اختر المريض...',
    'select_doctor_prompt': 'اختر الطبيب المعالج...',
    'search_doctor': 'البحث عن طبيب...',
    'search_patient': 'البحث عن مريض...',
    'no_patients_found': 'لم يتم العثور على مرضى مطابِقين',
    'no_doctors_found': 'لم يتم العثور على أطباء مطابِقين',
    'date_time': 'التاريخ والوقت',
    'status': 'الحالة',
    'select_session_type': 'اختر نوع الجلسة السريرية...',
    'other': 'أخرى / تصنيف مخصص',
    'update': 'تحديث البيانات',
    'confirm': 'تأكيد الحجز',
    'unassigned': 'غير محدد بعد',
    'click_to_schedule': '＋ اضغط لحجز موعد في الساعة {time}',

    // Reports View
    'clinic_audit_report': 'تقرير المراجعة السريرية الشامل',
    'flat_spreadsheet_view': 'تقرير مسطح مفصل يوضح الجلسات المسجلة، المعاملات المالية، السلف، والمصروفات المستهلكة.',
    'print_sheet': 'طباعة التقرير',
    'evolve_clinical_suite': 'مجموعة إدارة عيادة ريفايف المتكاملة',
    'daily_practice_report': 'التقرير اليومي للعيادة',
    'weekly_practice_report': 'التقرير الأسبوعي للعيادة',
    'bi_weekly_practice_report': 'التقرير النصف شهري للعيادة',
    'tri_weekly_practice_report': 'تقرير الثلاثة أسابيع للعيادة',
    'custom_range_report': 'تقرير الفترة المخصصة',
    'monthly_practice_report': 'التقرير الشهري للعيادة',
    'period': 'الفترة الزمنية:',
    'doctor_label': 'الطبيب المعالج:',
    'generated_label': 'تاريخ الاستخراج:',
    'patients_treated': 'المرضى الذين تم علاجهم',
    'sessions_logged': 'الجلسات العلاجية المنجزة',
    'revenue_realized': 'الإيرادات المحققة',
    'net_revenue': 'صافي الإيرادات للعيادة',
    'treatment_sessions_sheet': '1. سجل الجلسات السريرية والتأهيلية المنجزة',
    'time_date': 'الوقت / التاريخ',
    'patient_name': 'اسم المريض',
    'session_no': 'رقم الجلسة',
    'treatment_rehab_protocols': 'البروتوكولات العلاجية والتأهيلية المنفذة',
    'progress_observations': 'ملاحظات تقدم الحالة ومستوى الألم',
    'no_rehab_sessions_logged': 'لا توجد جلسات تأهيل سريرية مسجلة خلال الفترة المحددة.',
    'realized_revenue_sheet': '2. سجل الإيرادات والمقبوضات المالية للمرضى',
    'payment_type': 'طريقة الدفع / الخدمة',
    'acquisition_details': 'تفاصيل المعاملة المالية',
    'net_paid': 'المبلغ المدفوع صافياً',
    'prepaid_package': 'باقة مسبقة الدفع (مجموعة {count} جلسات)',
    'per_session_treatment': 'جلسة علاجية فردية',
    'no_billing_receipts': 'لا توجد إيصالات سداد أو معاملات مالية مسجلة في هذه الفترة.',
    'staff_doctor_loans': '3. سجل سلفيات وحسابات الأطباء والموظفين الإداريين',
    'role': 'الصفة الوظيفية',
    'note': 'ملاحظات وتفاصيل السلفة',
    'settled': 'تمت تسويتها',
    'no_loans_recorded': 'لا توجد سلفيات أو مسحوبات مسجلة خلال هذه الفترة.',
    'total_loans': 'إجمالي السلفيات المسحوبة',
    'clinic_wastes_sheet': '4. سجل المصروفات والمستهلكات الطبية والمواد المستهلكة',
    'item': 'المادة المستهلكة',
    'qty': 'الكمية',
    'unit_cost': 'سعر الوحدة',
    'total': 'الإجمالي',
    'no_waste_items': 'لا توجد مستهلكات أو مصروفات مسجلة خلال هذه الفترة.',
    'total_wastes': 'إجمالي المصروفات والمستهلكات',
    'shift_attendance_log': '5. سجل حضور وانصراف الأطباء وموظفي النوبات',
    'classification': 'التصنيف السريري',
    'check_in': 'حضور (دخول)',
    'check_out': 'انصراف (خروج)',
    'hours_worked': 'ساعات العمل الفعلية',
    'no_attendance_logs': 'لا توجد سجلات حضور أو انصراف مسجلة خلال هذه الفترة المحددة.',
    'daily_consolidated_log': '6. السجل اليومي الموحد لإحصائيات العيادة',
    'patient_volume': 'عدد زيارات المرضى',
    'aggregate_revenue': 'مجموع الإيرادات اليومية',
    'biometric_system_isolated': 'التحقق والمصادقة الأمنية لبيانات الأجهزة والعيادة',
    'summary_extracted_local': 'تم استخراج وتلخيص هذا التقرير تلقائياً من قاعدة البيانات المحلية المشفرة. اجتاز اختبار المطابقة والتحقق الأمني.',
    'authorized_physiotherapist': 'معتمد ومصدق عليه من الطبيب الفيزيائي المسؤول عن الفرع.',
    'practitioner_clinician_signature': 'توقيع الطبيب الممارس المسؤول',
    'verification_stamp_log': 'ختم واعتماد إدارة العيادة',
    'day_opt': 'يوم',
    'week_opt': 'أسبوع',
    '2weeks_opt': 'أسبوعين',
    '3weeks_opt': '3 أسابيع',
    'month_opt': 'شهر كامل',
    'custom_range_opt': 'فترة مخصصة',
    'select_month_opt': 'اختر شهراً معيناً',
    'all_doctors': 'جميع الأطباء المعالجين',
    'to_date_connector': 'إلى',

    // Finance Management View
    'payroll_tab': 'رواتب الموظفين',
    'loans_tab': 'السلف والعهد المالية',
    'wastes_tab': 'المصروفات والمستهلكات',
    'daily_tab': 'الملخص اليومي',
    'services_tab': 'الخدمات والباقات',
    'financial_operations': 'إدارة العمليات المالية والرواتب',
    'financial_operations_desc': 'احتساب مستحقات الأطباء والرواتب الأساسية والعمولات، وإدارة عهد وسلف الفريق، وتحديد أسعار الخدمات والزيارات.',
    'monthly_revenue_indicator': 'إجمالي إيرادات الشهر الحالي',
    'staff_payroll_ledger': 'كشف مستحقات الأطباء والمساعدين السريري',
    'search_practitioners': 'البحث عن معالج أو مساعد...',
    'practitioner_details': 'بيانات الممارس والوظيفة',
    'base_salary': 'الراتب الأساسي (جنيه)',
    'dynamic_commission': 'عمولات الجلسات الإضافية',
    'calculated_payout': 'صافي المبلغ المستحق للدفع',
    'ledger_actions': 'إجراءات الحساب',
    'calculate_salary': 'احتساب المستحقات',
    'salary_saved': 'تم الحفظ والاعتماد',
    'edit_payroll_calculations': 'تعديل احتساب رواتب الموظفين للفرع الحالي',
    'sessions_completed_in': 'الجلسات السريرية المنجزة لشهر {month}',
    'pt_sessions': 'جلسات العلاج الطبيعي',
    'nutrition_sessions': 'جلسات التغذية العلاجية',
    'lymphatic_sessions': 'جلسات التصريف الليمفاوي',
    'other_sessions': 'جلسات أخرى متنوعة',
    'save_salary_record': 'حفظ واعتماد كشف الراتب',
    'loans_advances_management': 'إدارة السلف المالية والقروض المستردة للفريق',
    'issue_new_loan': 'صرف سلفة مالية جديدة لعضو الفريق',
    'settle_all_loans': 'تسوية جميع السلفيات النشطة للشهر',
    'remaining_deductions': 'المستحقات المتبقية للاسترداد',
    'loans_history_for': 'سجل السلفيات المصروفة لشهر {month}',
    'no_loans_found_period': 'لم يتم تسجيل أي سلفيات نشطة أو تمت تسويتها خلال هذا الشهر.',
    'wastes_expense_tracking': 'تتبع المصاريف والنفايات الاستهلاكية للعيادة',
    'record_waste_purchase': 'تسجيل بند شراء مستهلكات أو مصاريف جديدة',
    'daily_expense_logs': 'سجل المصاريف الاستهلاكية لليوم المحدد',
    'total_expense': 'إجمالي المصاريف المسجلة اليوم',
    'no_expense_logged_day': 'لم يتم تسجيل أي مصاريف أو مستهلكات لهذا اليوم المحدد.',
    'service_pricing_library': 'دليل أسعار الخدمات وباقات الجلسات السريرية',
    'define_new_service': 'تعريف وإضافة خدمة علاجية جديدة',
    'service_cost': 'التكلفة الإجمالية (جنيه)',
    'number_of_sessions': 'عدد الجلسات المشمولة في الخدمة',
    'actions': 'الإجراءات والخيارات',
    'edit': 'تعديل',
    'delete': 'حذف البند',
    'edit_service': 'تعديل الخدمة العلاجية',
    'update_service': 'حفظ وتحديث أسعار الخدمة',
    'confirm_delete_service': 'هل أنت متأكد من حذف هذه الخدمة السريرية نهائياً من المكتبة؟',

    // Client Profile View
    'sync_local_database': 'مزامنة الشبكة المحلية',
    'syncing_local': 'جاري تحديث البيانات سريرياً...',
    'print_patient_report': 'طباعة التقرير الشامل',
    'pt_profile_tab': 'ملف العلاج الطبيعي',
    'nutrition_profile_tab': 'ملف التغذية',
    'lymphatic_profile_tab': 'ملف الليمفاوي',
    'medical_records_tab': 'السجل والتقارير الطبية',
    'home_exercises_tab': 'البرنامج المنزلي',
    'clinical_exercises_tab': 'التمارين السريرية',
    'session_finance_tab': 'الحسابات والمعاملات',
    'recovery_insights_tab': 'مستويات التعافي والألم',
    'edit_patient_profile': 'تعديل بيانات الملف السريري للمريض',
    'save_changes_btn': 'حفظ التحديثات',
    'diagnosis_history_section': 'التشخيص الطبي والتاريخ المرضي',
    'no_prior_medical_history': 'لا يوجد تاريخ طبي مسجل مسبقاً لهذا المريض.',
    'patient_access_pin_lbl': 'رمز مرور دخول المريض للبوابة',
    'sync_portal_btn': 'مزامنة بوابة المريض الإلكترونية',
    'synchronizing': 'جاري الرفع السحابي...',
    'patient_clinical_profiles': 'الملفات والبرامج العلاجية النشطة للمريض',
    'add_pt_profile': 'إنشاء ملف علاج طبيعي جديد',
    'add_nutrition_profile': 'إنشاء ملف تغذية علاجية جديد',
    'add_lymphatic_profile': 'إنشاء ملف تصريف ليمفاوي جديد',
    'activate_account': 'تنشيط الملف',
    'archive_account': 'أرشفة السجل',
    'purge_record_btn': 'حذف السجل نهائياً',
    'medical_documents_header': 'المستندات والتقارير الطبية للمريض',
    'diagnostic_imagery_desc': 'الأشعة السينية، الرنين المغناطيسي، التحاليل الطبية والتقارير الخارجية.',
    'import_record_btn': 'استيراد مستند جديد',
    'no_digital_records_found': 'لا توجد ملفات أو مستندات رقمية مرفقة للمريض.',
    'securely_store_pdfs': 'قم بحفظ مستندات الأشعة والتحاليل في مكان آمن لسهولة الوصول إليها لاحقاً.',
    'open_document_tooltip': 'فتح وعرض المستند',
    'reveal_in_system_tooltip': 'عرض موقع الملف في النظام',
    'record_payment_btn': 'تسجيل معاملة مالية جديدة',
    'active_package_status': 'حالة باقة الجلسات مسبقة الدفع الحالية للمريض',
    'realtime_sync_timeline': 'مزامنة حية مع الجلسات المنجزة على جدول المواعيد',
    'total_purchased': 'إجمالي الجلسات المشحونة',
    'sessions_used': 'الجلسات التي استهلكها المريض',
    'sessions_left': 'الجلسات العلاجية المتبقية له',
    'service_classification': 'التصنيف والخدمة الطبية المسجلة',
    'select_service_type': 'اختر الخدمة من الدليل المعتمد...',
    'session_count_label': 'عدد الجلسات المعتمدة للباقة',
    'total_transaction_value': 'إجمالي القيمة المسددة (جنيه)',
    'fixed_rate_sync_notice': '* يتم تحديد السعر تلقائياً بناءً على مكتبة الخدمات والأسعار المعتمدة للعيادة.',
    'authenticate_record': 'اعتماد وتسجيل المعاملة المالية في الخزينة',
    'no_financial_records': 'لا توجد فواتير أو إيصالات سداد مسجلة لهذا المريض.',
    'transaction_date': 'تاريخ السداد',
    'service_details': 'تفاصيل الخدمة العلاجية',
    'volume_notes': 'الكمية / ملاحظات السداد',
    'net_amount': 'القيمة الإجمالية المدفوعة',
    'payment_notes_placeholder': 'ملاحظات إضافية حول السداد والتقسيط...',
    'sessions_unit': 'جلسة/جلسات',
    'patient_access_portal': 'بوابة دخول المريض الذكية',
    'scan_code_portal': 'امسح الرمز بكاميرا هاتف المريض لتفعيل البوابة الإلكترونية ومتابعة تمارينه السريرية والمنزلية.',
    'done_btn': 'تم بنجاح',
    'active_profile_confirm_delete': 'هل أنت متأكد من حذف ملف {type} للمريض نهائياً؟ سيؤدي ذلك إلى مسح جميع التقييمات والأهداف المرتبطة به.',
    'purge_client_confirm': 'تحذير حرج: هل تريد حذف ملف المريض {name} نهائياً وبشكل كامل من خوادم وقواعد بيانات العيادة؟ هذا الإجراء لا يمكن التراجع عنه.',
    'initial_setup': 'الإعداد الأولي للنظام',
    'init_admin_acc': 'إنشاء وتهيئة حساب مدير النظام',
    'new_password': 'كلمة المرور الجديدة',
    'complete_secure_setup': 'إتمام إعداد الحساب الآمن',
    'initializing': 'جاري التهيئة والإنشاء...',
    'sys_config_mode_footer': 'وضع تهيئة النظام | عيادة ريفايف الطبية 2026',
    'pwd_mismatch_error': 'كلمتا المرور غير متطابقتين. يرجى التحقق.',
    'pwd_length_error': 'متطلب أمني: يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.',
    'setup_failed_error': 'فشل بدء وتهيئة الإعداد الأولي.',
    'critical_setup_error': 'حدث خطأ حرج في النظام أثناء الإعداد الأولي.',
    'welcome_branch': 'مرحباً، {name}. اختر فرعاً لإدارته والعمل عليه.',
    'no_branches_found': 'لم يتم العثور على فروع مسجلة. يرجى الاتصال بمسؤول النظام.',
    'branch_active_lbl': 'الفرع #{id} · نشط حالياً',
    'branch_select_footer': 'يعمل كل فرع ببيانات منفصلة ومشفرة تماماً. يحدد اختيارك الفرع النشط لجلسة العمل الحالية.',
    'version_multibranch_footer': 'الإصدار 4.0.0-REVIVE · نسخة الفروع المتعددة الموحدة',
    'active_loans': 'السلف النشطة',
    'reset_month': 'إعادة تعيين الشهر',
    'no_staff_doctors_found': 'لم يتم العثور على أطباء أو موظفين.',
    'total_loaned': 'إجمالي السلف',
    'add_loan': 'إضافة سلفة',
    'amount': 'المبلغ',
    'note_optional': 'ملاحظة (اختياري)',
    'reason_loan_placeholder': 'سبب السلفة...',
    'save': 'حفظ',
    'mark_settled_tooltip': 'تحديد كمسواة',
    'delete_perm_tooltip': 'حذف نهائياً',
    'no_active_loans_period': 'لا توجد سلف نشطة لهذه الفترة.',
    'no_loans_found': 'لم يتم العثور على سلفيات.',
    'days_with_waste': 'الأيام التي تحتوي على مصروفات',
    'daily_total': 'الإجمالي اليومي',
    'add_item': 'إضافة بند',
    'item_name': 'اسم البند',
    'quantity': 'الكمية',
    'unit_cost_egp': 'سعر الوحدة (جنيه)',
    'item_name_placeholder': 'مثال: قفازات، شاي، أكواب...',
    'item_header': 'البند',
    'qty_header': 'الكمية',
    'unit_cost_header': 'سعر الوحدة',
    'total_header': 'الإجمالي',
    'day_total': 'إجمالي اليوم',
    'no_waste_recorded_day': 'لم يتم تسجيل أي مصروفات لهذا اليوم.',
    'click_add_item_desc': 'اضغط على "إضافة بند" لتسجيل المصروفات الطبية والإدارية.',
    'gross_revenue': 'إجمالي الإيرادات',
    'loans': 'السلفيات',
    'wastes': 'المصروفات',
    'net_revenue_lbl': 'صافي الإيرادات',
    'from_payments': 'من المقبوضات والمدفوعات',
    'record_singular': 'سجل',
    'records_plural': 'سجلات',
    'item_singular': 'بند',
    'items_plural': 'بنود',
    'net_gain': 'صافي ربح',
    'net_loss': 'صافي خسارة',
    'revenue_breakdown': 'تفاصيل الإيرادات',
    'loans_issued': 'السلف المنصرفة',
    'clinic_wastes': 'مصروفات العيادة',
    'net_clear_revenue': 'صافي الإيراد المخلص',
    'loans_on_day': 'السلف المنصرفة في هذا اليوم',
    'waste_items_on_day': 'المصروفات المستهلكة في هذا اليوم',
    'no_financial_activity_day': 'لا توجد أي حركة مالية مسجلة في هذا اليوم.',
    'session_type_library': 'مكتبة أنواع الجلسات والخدمات',
    'manage_session_types_desc': 'إدارة أسعار الخدمات وباقات الجلسات المختلفة المعتمدة بالعيادة.',
    'add_new_session_type': 'إضافة نوع جلسة جديدة',
    'name': 'الاسم',
    'sessions_package_optional': 'عدد الجلسات في الباقة (اختياري)',
    'leave_blank_single': 'اتركه فارغاً للجلسة المفردة',
    'add_session_type_btn': 'إضافة نوع الجلسة',
    'no_session_types_defined': 'لم يتم تحديد أي نوع جلسة بعد.',
    'add_session_types_above_desc': 'قم بإضافة أنواع الجلسات أعلاه لتتمكن من استخدامها في حسابات المرضى.',
    'egp_per_session': 'جنيه للجلسة الواحدة',
    'sessions_in_package_desc': 'جلسة في الباقة',
    'all_filter': 'الكل',
    'active_filter': 'النشطة',
    'settled_filter': 'تمت تسويتها',
    'ai_clinical_assistant': 'المساعد السريري بالذكاء الاصطناعي',
    'ai_subtitle': 'دعم القرار السريري القائم على الأدلة وتخطيط برامج العلاج والتأهيل.',
    'patient_context_optional': 'سياق المريض الحالي (اختياري)',
    'general_query_no_context': 'استعلام عام (بدون سياق مريض معين)',
    'clinical_dilemma_question': 'المعضلة السريرية أو استفسار العلاج والتأهيل',
    'ai_textarea_placeholder': 'مثال: قم بتحليل التاريخ المرضي للمريض واقتراح خطة تأهيلية متعددة المراحل للحالة المزمنة...',
    'data_remains_encrypted_local': 'تظل البيانات مشفرة ومحفوظة محلياً',
    'consult_assistant': 'استشارة المساعد الذكي',
    'generating_analysis': 'جاري تحليل وتوليد الخطة العلاجية...',
    'system_error': 'خطأ في النظام',
    'clinical_synthesis': 'التوليف والتشخيص السريري الذكي',
    'ai_processed': 'معالجة بالذكاء الاصطناعي',
    'synthesis_failed': 'فشل تحليل الحالة',
    'copy_to_clinical_notes': 'نسخ إلى الملاحظات السريرية للمريض',
    'ai_error_unexpected': 'حدث خطأ غير متوقع أثناء توليف البيانات بالذكاء الاصطناعي.',
    'credentials_approvals': 'الاعتمادات والموافقات على الحسابات',
    'credentials_approvals_desc': 'مراجعة واعتماد طلبات إنشاء الحسابات والوصول للأطباء والموظفين.',
    'refresh_requests': 'تحديث الطلبات',
    'search_account_requests_placeholder': 'البحث باسم المستخدم، اسم المعالج، الدور، أو الفرع...',
    'all_requests_filter': 'جميع الطلبات',
    'no_requests_found': 'لم يتم العثور على أي طلبات',
    'no_requests_found_desc': 'لا توجد طلبات تسجيل مطابقة لخيارات التصفية الحالية. طلبات التسجيل الجديدة ستظهر هنا تلقائياً.',
    'branch_header': 'الفرع',
    'role_header': 'الدور',
    'name_header': 'الاسم',
    'username_header': 'اسم المستخدم',
    'date_header': 'التاريخ',
    'status_header': 'الحالة',
    'actions_header': 'الإجراءات',
    'approve_btn': 'اعتماد',
    'deny_btn': 'رفض',
    'processed_status': 'معالج ومكتمل',
    'toast_failed_load_requests': 'فشل تحميل طلبات التسجيل.',
    'toast_request_approved': 'تم اعتماد وتفعيل الحساب "{username}" بنجاح!',
    'toast_request_approved_error': 'حدث خطأ أثناء اعتماد الحساب: {error}',
    'toast_request_denied': 'تم رفض طلب تسجيل الحساب "{username}".',
    'toast_request_denied_error': 'حدث خطأ أثناء رفض الطلب: {error}',
    'confirm_approve_request': 'هل أنت متأكد من الموافقة على طلب تفعيل حساب "{username}"؟',
    'confirm_deny_request': 'هل أنت متأكد من رفض طلب حساب "{username}"؟',
    'shift_attendance_console': 'لوحة حضور وانصراف المناوبات',
    'shift_attendance_desc': 'تسجيل أوقات الحضور والانصراف للأطباء وموظفي العيادة.',
    'toast_failed_load_attendance': 'فشل تحميل سجلات الحضور والانصراف.',
    'toast_clock_in_success': 'تم تسجيل حضور {username} في {time} بنجاح!',
    'toast_clock_in_failed': 'فشل تسجيل حضور {username}',
    'toast_clock_out_success': 'تم تسجيل انصراف {username} في {time} بنجاح!',
    'toast_clock_out_failed': 'فشل تسجيل انصراف {username}',
    'toast_sys_error_occurred': 'حدث خطأ في النظام',
    'time_station': 'محطة تسجيل الوقت',
    'welcome_username': 'مرحباً، {username}!',
    'role_label': 'الصفة الوظيفية:',
    'clock_in_btn': 'تسجيل الحضور (دخول)',
    'clock_out_btn': 'تسجيل الانصراف (خروج)',
    'checked_in_at': 'حضر في {time}',
    'checked_out_at': 'انصرف في {time}',
    'shift_logs_attendance': 'حضور الموظفين والمناوبات',
    'viewing_shift_history': 'عرض سجل حضور اليوم السريري المحدد.',
    'search_staff_role_placeholder': 'البحث عن موظف أو دور...',
    'select_date_lbl': 'اختر التاريخ:',
    'syncing_shift_history': 'جاري مزامنة سجل المناوبات...',
    'no_clinical_users_registered': 'لا يوجد موظفون أو أطباء مسجلون في النظام.',
    'classification_header': 'التصنيف الوظيفي',
    'arrival_header': 'الحضور (تسجيل الدخول)',
    'departure_header': 'الانصراف (تسجيل الخروج)',
    'daily_status_header': 'حالة اليوم',
    'you_tag': 'أنت',
    'check_in_btn': 'تسجيل دخول',
    'check_out_btn': 'تسجيل خروج',
    'completed_status': 'مكتمل',
    'on_duty_status': 'في الخدمة حالياً',
    'absent_pending_status': 'غائب / قيد الانتظار',
    // User Management
    'users_tab_lbl': 'المستخدمين',
    'doctors_tab_lbl': 'الأطباء',
    'clinic_team_mgmt_title': 'إدارة فريق العيادة',
    'clinic_team_mgmt_desc': 'إدارة حسابات الموظفين وصلاحيات الوصول. يمكنك إضافة أعضاء فريق جدد أو تحديث بيانات الأمان للحسابات الحالية.',
    'add_team_member_btn': 'إضافة عضو فريق',
    'search_by_username_placeholder': 'البحث باسم المستخدم...',
    'active_branch_lbl': 'الفرع النشط:',
    'register_security_creds': 'تسجيل بيانات الأمان والوصول',
    'access_privilege_role': 'دور صلاحية الوصول',
    'role_owner': 'المالك (مدير خارق)',
    'role_admin': 'مسؤول (وصول كامل)',
    'role_cfo': 'المدير المالي (CFO)',
    'role_staff': 'موظف عيادة (عمليات يومية)',
    'role_doctor': 'طبيب معالج / أخصائي',
    'assign_doctor_profile': 'ربط ملف الطبيب المعالج',
    'select_doctor_profile_prompt': 'اختر ملف الطبيب المعالج...',
    'assigned_branches_ctrl': 'الفروع المعينة (صلاحيات التحكم)',
    'default_operating_branch': 'فرع التشغيل الافتراضي',
    'security_pwd': 'كلمة المرور الأمنية',
    'auth_register_account': 'توثيق وتسجيل الحساب',
    'active_accounts_section': 'الحسابات النشطة',
    'staff_member_username_hdr': 'عضو الفريق / اسم المستخدم',
    'access_role_hdr': 'دور الوصول',
    'all_branches_owner': 'جميع الفروع (المالك)',
    'no_branches_assigned': 'لا توجد فروع معينة',
    'status_active': 'نشط',
    'status_frozen': 'مجمد',
    'assign_branches_tooltip': 'تعيين الفروع',
    'reset_creds_tooltip': 'إعادة تعيين كلمة المرور',
    'revoke_access_tooltip': 'سحب صلاحية الوصول',
    'frozen_accounts_section': 'الحسابات المجمدة',
    'doctor_mgmt_title': 'إدارة الأطباء',
    'doctor_mgmt_desc': 'تهيئة الأطباء والممارسين النشطين. سيتم استبعاد الأطباء المجمدين من خيارات التوقيع.',
    'add_doctor_btn': 'إضافة طبيب',
    'search_doctors_placeholder': 'البحث عن الأطباء بالاسم أو التخصص...',
    'modify_doctor_profile': 'تعديل ملف الطبيب:',
    'add_new_doctor_profile': 'إضافة ملف طبيب جديد',
    'doctor_name_lbl': 'اسم الطبيب',
    'specialty_lbl': 'التخصص',
    'profile_status_lbl': 'حالة الملف',
    'update_doctor_profile': 'تحديث ملف الطبيب',
    'register_doctor_profile': 'تسجيل ملف الطبيب',
    'credential_reset_title': 'إعادة تعيين بيانات الاعتماد',
    'reissuing_access_for': 'إعادة إصدار صلاحية الوصول لـ',
    'new_secure_pwd': 'كلمة مرور آمنة جديدة',
    'update_creds_btn': 'تحديث بيانات الاعتماد',
    'config_branch_access_for': 'تهيئة صلاحية الوصول للفرع لـ',
    'select_branches_lbl': 'اختر الفروع',
    // BioMetrics / AssessmentTab
    'full_body_scanning_protocol': 'بروتوكول فحص كامل الجسم',
    'report_auto_gen': 'توليد التقرير تلقائياً',
    'report_disabled': 'التقرير معطل',
    'export_report': 'تصدير التقرير',
    'findings_lbl': 'النتائج الإيجابية:',
    'search_body_region_placeholder': 'البحث حسب منطقة الجسم (مثل الكتف، الركبة، الظهر)...',
    'assessment_suffix': 'تقييم',
    'positive_finding_title': 'نتيجة إيجابية',
    'positive_finding_btn': 'إيجابي',
    'negative_cleared_title': 'سلبي / سليم',
    'negative_cleared_btn': 'سلبي',
    'clinical_positive_findings_hdr': 'النتائج السريرية الإيجابية',
    'biometric_assessment_report_sub': 'تقرير التقييم البيومتري للتعافي',
    'confirmed_finding_tag': 'نتيجة مؤكدة',
    'end_clinical_protocol_footer': 'نهاية بروتوكول التقييم السريري — المزامنة الآمنة نشطة',
    'bulk_data_mgmt': 'إدارة البيانات الضخمة',
    'bulk_data_mgmt_desc': 'استيراد أو تصدير مكتبة التقييمات الكاملة عبر ملف Excel',
    'column_guide_btn': 'دليل الأعمدة',
    'export_excel_btn': 'تصدير إكسل',
    'import_excel_btn': 'استيراد إكسل',
    'req_excel_cols': 'أسماء أعمدة إكسل المطلوبة',
    'add_new_clinical_region': 'إضافة منطقة سريرية جديدة',
    'initialize_region_btn': 'تهيئة وإضافة المنطقة',
    'remove_region_btn': 'حذف المنطقة',
    'rename_region_tooltip': 'إعادة تسمية المنطقة',
    'register_new_test_protocol': 'تسجيل بروتوكول فحص جديد',
    'link_test_btn': 'ربط الفحص',
    'syncing_biometrics': 'جاري مزامنة البيانات البيومترية...',
    'protocol_lbl': 'البروتوكول',
    'syncing_admin': 'جاري مزامنة لوحة التحكم للإدارة...',
    'exporting_lbl': 'جاري التصدير...',
    'importing_lbl': 'جاري الاستيراد...',
    'required_lbl': 'مطلوب',
    'col_guide_region_desc': 'اسم منطقة التقييم (مثال: "الكتف"). يتم إنشاؤه تلقائياً إذا لم يكن موجوداً.',
    'col_guide_name_desc': 'اسم الفحص السريري (مثال: "اختبار هوكينز-كينيدي").',
    'col_guide_desc_desc': 'وصف قصير اختياري لبروتوكول الفحص.',
    'add_region_placeholder': 'مثال: الفقرات العنقية، الورك، الكاحل...',
    'confirm_delete_region': 'هل أنت متأكد من حذف هذه المنطقة وجميع الفحوصات والنتائج المرتبطة بها؟',
    'confirm_delete_test': 'هل أنت متأكد من حذف هذا الفحص السريري؟',
    'test_name_placeholder': 'اسم الفحص',
    'test_desc_placeholder': 'وصف قصير',
    'test_name_eg_placeholder': 'اسم الفحص (مثال: اختبار هوكينز-كينيدي)',
    'test_desc_optional_placeholder': 'وصف قصير (اختياري)',
    'import_success_msg': '✓ تم استيراد {imported} فحوصات (تم تخطي {skipped}).',
    'import_failed_msg': '✗ فشل الاستيراد: {error}',
    'export_success_msg': '✓ تم التصدير بنجاح إلى {fileName}',
    'export_failed_msg': '✗ فشل التصدير: {error}',
    'shoulder': 'الكتف',
    'arm (biceps/triceps)': 'الذراع (العضلة ثنائية/ثلاثية الرؤوس)',
    'upper back': 'أعلى الظهر',
    'mid back': 'منتصف الظهر',
    'lower back': 'أسفل الظهر',
    'leg: anterior thigh': 'الساق: الفخذ الأمامي',
    'leg: posterior thigh': 'الساق: الفخذ الخلفي',
    'leg: knee': 'الساق: الركبة',
    'leg: calf': 'الساق: ربلة الساق (السمانة)',
    'cervical spine': 'الفقرات العنقية',
    'hip': 'الورك',
    'ankle': 'الكاحل',
    'hawkins-kennedy test': 'اختبار هوكينز-كينيدي',
    'neer test': 'اختبار نير',
    'empty can test': 'اختبار العلبة الفارغة',
    "speed's test": "اختبار سبيد",
    "yergason's test": "اختبار يرجاسون",
    "spurling's test": "اختبار سبورلينج",
    'slump test': 'اختبار الانحناء (Slump Test)',
    'straight leg raise': 'رفع الساق المستقيمة (SLR)',
    'faber test': 'اختبار فابر (FABER)',
    'thomas test': 'اختبار توماس',
    'popliteal angle test': 'اختبار زاوية المأبض (Popliteal Angle)',
    'lachman test': 'اختبار لاكمان',
    'mcmurray test': 'اختبار ماكموراي',
    'valgus stress test': 'اختبار إجهاد الأروح (Valgus)',
    'thompson test': 'اختبار تومسون',
    "homan's sign": "علامة هومان",
    'doctor_signature_req_error': 'توقيع الطبيب المعتمد مطلوب.',
    'red_flags_saved': 'تم حفظ العلامات الحمراء بنجاح.',
    'save_failed': 'فشل حفظ البيانات.',
    'subjective_updated': 'تم تحديث التقييم الذاتي بنجاح.',
    'new_assessment_saved': 'تم حفظ التقييم الذاتي الجديد بنجاح.',
    'objective_saved': 'تم حفظ التقييم الموضوعي بنجاح.',
    'assessment_deleted': 'تم حذف التقييم بنجاح.',
    'failed_to_delete': 'فشل حذف السجل.',
    'by_clinician': 'بواسطة:',
    'confirm_delete_assessment': 'هل أنت متأكد من حذف هذا التقييم الفيزيائي؟',
    'confirm_delete_session_plan': 'هل أنت متأكد من حذف خطة الجلسة هذه؟',
    'session_plan_deleted': 'تم حذف خطة الجلسة بنجاح.',
    'session_plan_updated': 'تم تحديث خطة الجلسة بنجاح.',
    'new_session_plan_saved': 'تم حفظ خطة الجلسة الجديدة بنجاح.',
    'cloned_from_latest_success': 'تم نسخ خطة آخر جلسة بنجاح.',
    'joint_name_placeholder_eg': 'مثال: الركبة',
    'angle_placeholder_eg': 'مثال: 120 درجة',
    'session_item_notes_placeholder': 'ملاحظات {itemName}...',
    'could_not_init_draft': 'لم نتمكن من إنشاء مسودة تقييم جديدة.',
    'session_history_lbl': 'سجل الجلسات العلاجية',
    // PhysicalTherapyProfile
    'red_flags_tab': 'العلامات الحمراء',
    'physical_assessment_tab': 'التقييم الفيزيائي',
    'special_tests_tab': 'الفحوصات الخاصة',
    'session_plan_tab': 'خطة الجلسة',
    'neuro_red_flags_screening': 'فحص العلامات العصبية الحمراء الحرجة',
    'neuro_red_flags_desc': 'يرجى تحديد جميع العلامات العصبية الحمراء المنطبقة. اختيار "لا يوجد" يلغي باقي العلامات.',
    'other_describe_lbl': 'أخرى — اكتب تفاصيل',
    'describe_other_red_flag_placeholder': 'صف العلامة الحمراء الأخرى بالتفصيل...',
    'doctor_signature_req': 'توقيع الطبيب المعتمد (مطلوب)',
    'select_assigning_clinician': 'اختر الطبيب الممارس المعين...',
    'saving_lbl': 'جاري الحفظ...',
    'subjective_assessment_title': 'التقييم الذاتي (الشكوى والأعراض)',
    'chief_complaint_lbl': 'الشكوى الرئيسية للمريض',
    'enter_chief_complaint_placeholder': 'اكتب الشكوى الرئيسية للمريض بالتفصيل...',
    'aggravating_factors_lbl': 'العوامل المسببة لزيادة الألم (المهيجة)',
    'enter_aggravating_placeholder': 'ما هي الحركات أو العوامل التي تزيد من حدة الألم؟...',
    'easing_factors_lbl': 'العوامل المقللة للألم (المريحة)',
    'enter_easing_placeholder': 'ما هي الحركات أو الوضعيات التي تخفف الألم؟...',
    'pain_scale_vas': 'مقياس شدة الألم (VAS 0-10)',
    'no_pain_0': 'لا يوجد ألم (0)',
    'moderate_5': 'ألم متوسط (5)',
    'worst_pain_10': 'أقصى ألم ممكن (10)',
    'irritability_lbl': 'سرعة استثارة الألم (التهيج)',
    'irritability_notes_placeholder': 'ملاحظات حول تهيج واستثارة الألم...',
    'nature_lbl': 'طبيعة الألم',
    'nature_notes_placeholder': 'ملاحظات حول طبيعة ونوع الألم...',
    'objective_assessment_title': 'التقييم الموضوعي (الفحص السريري)',
    'range_of_motion_title': 'المدى الحركي للمفاصل',
    'add_joint_btn': 'إضافة مفصل للفحص',
    'no_joint_assessments': 'لم يتم إضافة أي تقييم للمفاصل بعد',
    'joint_tbl_hdr': 'المفصل',
    'pain_tbl_hdr': 'ألم',
    'limitation_tbl_hdr': 'محدودية',
    'angle_tbl_hdr': 'الزاوية',
    'positive_special_tests_lbl': 'الفحوصات الخاصة الإيجابية (من قسم الفحوصات الخاصة)',
    'no_positive_findings_recorded': 'لم يتم تسجيل أي نتائج إيجابية للفحوصات الخاصة.',
    'palpation_notes_lbl': 'نتائج وملاحظات الجس باليد (Palpation)',
    'palpation_findings_placeholder': 'اكتب تفاصيل الفحص باليد ومناطق الألم عند اللمس...',
    'assessments_history_title': 'سجل تقييمات المريض',
    'new_btn': 'جديد',
    'no_assessments_recorded': 'لا توجد تقييمات مسجلة للمريض حتى الآن.',
    'draft_status': 'مسودة غير موقعة',
    'unsigned_lbl': 'غير موقع',
    'editing_physical_assessment': 'تعديل التقييم السريري الحالي',
    'new_physical_assessment': 'إنشاء تقييم سريري جديد',
    'saved_on_lbl': 'تم الحفظ في',
    'fill_subjective_first': 'يرجى ملء وتوقيع التقييم الذاتي أولاً للبدء',
    'clinical_assessment_library': 'مكتبة الفحوصات الطبية السريرية الخاصة',
    'search_region_test_placeholder': 'البحث عن منطقة جسم أو فحص طبي معين...',
    'no_regions_found_lbl': 'لم يتم العثور على أي مناطق مطابقة',
    'session_plan_title': 'خطة وتفاصيل الجلسة العلاجية',
    'editing_session_plan': 'تعديل خطة الجلسة',
    'new_session_plan': 'خطة جلسة علاجية جديدة',
    'modify_session_plan_desc': 'تعديل تفاصيل وإجراءات الجلسة العلاجية التي تم تسجيلها مسبقاً.',
    'new_session_plan_desc': 'اختر العلاجات والأدوات والتقنيات المستخدمة لتوثيق الجلسة الحالية.',
    'clone_from_latest_btn': 'نسخ من آخر جلسة',
    'selected_unit': 'محدد',
    'specify_other_treatment_placeholder': 'اكتب الإجراء العلاجي الآخر بالتفصيل...',
    'red_flag_myelopathy': 'اعتلال النخاع الشوكي (Myelopathy)',
    'red_flag_cauda_equina': 'متلازمة ذيل الحصان (Cauda Equina)',
    'red_flag_drop_foot': 'سقوط القدم (Drop Foot)',
    'red_flag_urinary_incontinence': 'سلس البول (Urinary Incontinence)',
    'red_flag_motor_weakness': 'ضعف حركي عضلي (Motor Weakness)',
    'red_flag_other': 'علامات أخرى',
    'red_flag_no': 'لا توجد علامات حمراء عصبية',
    'irritability_high': 'عالي (High)',
    'irritability_mod': 'متوسط (Mod)',
    'irritability_low': 'منخفض (Low)',
    'nature_inflammatory': 'التهابي (Inflammatory)',
    'nature_mechanical': 'ميكانيكي (Mechanical)',
    'nature_neural': 'عصبي (Neural)',
    'session_plan_sec_electrotherapy': 'العلاج الكهربائي والحراري (Electrotherapy)',
    'session_plan_sec_manual_therapy': 'العلاج اليدوي والتحريك (Manual Therapy)',
    'session_plan_sec_tools': 'الأدوات والتقنيات (Tools)',
    'session_plan_item_tens': 'التحفيز الكهربائي للأعصاب (TENS)',
    'session_plan_item_nmes': 'التحفيز الكهربائي للعضلات (NMES)',
    'session_plan_item_hot_pack': 'الكمادات الساخنة (Hot Pack)',
    'session_plan_item_laser': 'العلاج بالليزر (Laser)',
    'session_plan_item_mobilisation': 'تحريك المفاصل (Mobilisation)',
    'session_plan_item_mobilisation_with_movement': 'التحريك مع الحركة (Mobilisation with Movement)',
    'session_plan_item_manipulation': 'التقويم اليدوي للمفاصل (Manipulation)',
    'session_plan_item_manual_soft_tissue_release': 'تحرير الأنسجة الرخوة يدوياً (Manual Soft Tissue Release)',
    'session_plan_item_dry_needle': 'الإبر الجافة (Dry Needle)',
    'session_plan_item_dry_cupping': 'الحجامة الجافة (Dry Cupping)',
    'session_plan_item_kinesio_taping': 'الشريط اللاصق الرياضي (Kinesio Taping)',
    'session_plan_item_rigid_tape': 'الشريط اللاصق الداعم الصلب (Rigid Tape)',
    'session_plan_item_blade_iastm': 'العلاج بالأدوات المعدنية (Blade/IASTM)',
    'session_plan_item_bfr': 'تمارين تقييد تدفق الدم (BFR)',
    'session_plan_item_other': 'إجراء علاجي آخر',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('pt_language') as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  useEffect(() => {
    localStorage.setItem('pt_language', language);
    const dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = language;

    // TODO(security): Safely dynamically import the Cairo font stylesheet for Arabic formatting
    if (language === 'ar') {
      if (!document.getElementById('cairo-font-link')) {
        const link = document.createElement('link');
        link.id = 'cairo-font-link';
        link.rel = 'stylesheet';
        link.href = 'https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;500;600;700;800;900&display=swap';
        document.head.appendChild(link);
      }
      document.body.style.fontFamily = "'Cairo', 'Noto Sans', sans-serif";
    } else {
      document.body.style.fontFamily = "";
    }
  }, [language]);

  const t = (key: string, defaultValue?: string): string => {
    return translations[language]?.[key] || defaultValue || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';
  const isAr = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir, isAr }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
