const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getClients: () => ipcRenderer.invoke('get-clients'),
  createClient: (clientData) => ipcRenderer.invoke('create-client', clientData),
  getClient: (clientId) => ipcRenderer.invoke('get-client', clientId),
  updateClient: (clientId, clientData) => ipcRenderer.invoke('update-client', clientId, clientData),
  getSessions: (clientId) => ipcRenderer.invoke('get-sessions', clientId),
  createSession: (sessionData) => ipcRenderer.invoke('create-session', sessionData),
  updateSession: (id, sessionData) => ipcRenderer.invoke('update-session', id, sessionData),
  deleteSession: (id) => ipcRenderer.invoke('delete-session', id),
  updateAssessment: (id, data) => ipcRenderer.invoke('update-assessment', id, data),
  deleteAssessment: (id) => ipcRenderer.invoke('delete-assessment', id),
  getPayments: (clientId) => ipcRenderer.invoke('get-payments', clientId),
  createPayment: (paymentData) => ipcRenderer.invoke('create-payment', paymentData),
  updatePayment: (paymentData) => ipcRenderer.invoke('update-payment', paymentData),
  getAppointments: (doctorId) => ipcRenderer.invoke('get-appointments', doctorId),
  createAppointment: (appointmentData) => ipcRenderer.invoke('create-appointment', appointmentData),
  updateAppointment: (data) => ipcRenderer.invoke('update-appointment', data),
  deleteAppointment: (id) => ipcRenderer.invoke('delete-appointment', id),
  getDashboardStats: (showAllTime) => ipcRenderer.invoke('get-dashboard-stats', showAllTime),
  resetDashboard: () => ipcRenderer.invoke('reset-dashboard'),
  getReportStats: (dateRange) => ipcRenderer.invoke('get-report-stats', dateRange),
  deleteClient: (clientId) => ipcRenderer.invoke('delete-client', clientId),
  toggleClientStatus: (clientId, status) => ipcRenderer.invoke('toggle-client-status', clientId, status),
  uploadDocument: (clientId) => ipcRenderer.invoke('upload-document', clientId),
  getDocuments: (clientId) => ipcRenderer.invoke('get-documents', clientId),
  openDocument: (filePath) => ipcRenderer.invoke('open-document', filePath),
  exportBackup: () => ipcRenderer.invoke('export-backup'),
  getTodayAppointments: () => ipcRenderer.invoke('get-today-appointments'),
  getDoctors: () => ipcRenderer.invoke('get-doctors'),
  addDoctor: (data) => ipcRenderer.invoke('add-doctor', data),
  updateDoctor: (id, data) => ipcRenderer.invoke('update-doctor', id, data),
  deleteDoctor: (id) => ipcRenderer.invoke('delete-doctor', id),
  getActiveDoctors: () => ipcRenderer.invoke('get-active-doctors'),
  createSession: (sessionData) => ipcRenderer.invoke('create-session', sessionData),
  getAssessments: (clientId) => ipcRenderer.invoke('get-assessments', clientId),
  createAssessment: (data) => ipcRenderer.invoke('create-assessment', data),
  getAuditLogs: (clientId) => ipcRenderer.invoke('get-audit-logs', clientId),
  getRecoveryStats: (clientId) => ipcRenderer.invoke('get-recovery-stats', clientId),
  askAi: (data) => ipcRenderer.invoke('ask-ai', data),
  getAssessmentStructure: () => ipcRenderer.invoke('get-assessment-structure'),
  saveAssessmentResult: (data) => ipcRenderer.invoke('save-assessment-result', data),
  getClientAssessmentResults: (clientId) => ipcRenderer.invoke('get-client-assessment-results', clientId),
  getTestHistory: (data) => ipcRenderer.invoke('get-test-history', data),
  addAssessmentRegion: (name) => ipcRenderer.invoke('add-assessment-region', name),
  addAssessmentTest: (data) => ipcRenderer.invoke('add-assessment-test', data),
  deleteAssessmentTest: (testId) => ipcRenderer.invoke('delete-assessment-test', testId),
  deleteAssessmentRegion: (regionId) => ipcRenderer.invoke('delete-assessment-region', regionId),
  updateAssessmentRegion: (data) => ipcRenderer.invoke('update-assessment-region', data),
  updateAssessmentTest: (data) => ipcRenderer.invoke('update-assessment-test', data),
  getClientProgressStats: (clientId) => ipcRenderer.invoke('get-client-progress-stats', clientId),
  getClientPackageStatus: (clientId) => ipcRenderer.invoke('get-client-package-status', clientId),
  getExercises: () => ipcRenderer.invoke('get-exercises'),
  addExerciseRegion: (name) => ipcRenderer.invoke('add-exercise-region', name),
  deleteExerciseRegion: (id) => ipcRenderer.invoke('delete-exercise-region', id),
  addExercise: (data) => ipcRenderer.invoke('add-exercise', data),
  deleteExercise: (id) => ipcRenderer.invoke('delete-exercise', id),
  updateExerciseRegion: (data) => ipcRenderer.invoke('update-exercise-region', data),
  updateExercise: (data) => ipcRenderer.invoke('update-exercise', data),
  getClientExercises: (clientId) => ipcRenderer.invoke('get-client-exercises', clientId),
  assignExercise: (data) => ipcRenderer.invoke('assign-exercise', data),
  removeClientExercise: (id) => ipcRenderer.invoke('remove-client-exercise', id),
  logExerciseProgress: (data) => ipcRenderer.invoke('log-exercise-progress', data),
  exportExercisesExcel: () => ipcRenderer.invoke('export-exercises-excel'),
  importExercisesExcel: () => ipcRenderer.invoke('import-exercises-excel'),
  exportAssessmentsExcel: () => ipcRenderer.invoke('export-assessments-excel'),
  importAssessmentsExcel: () => ipcRenderer.invoke('import-assessments-excel'),
  pushPatientPlan: (data) => ipcRenderer.invoke('push-patient-plan', data),
  getHighPainAlerts: () => ipcRenderer.invoke('get-high-pain-alerts'),
  getAllPainLogs: () => ipcRenderer.invoke('get-all-pain-logs'),
  getPainTestResults: () => ipcRenderer.invoke('get-pain-test-results'),
  showItemInFolder: (filePath) => ipcRenderer.invoke('show-item-in-folder', filePath),
  checkUsersExist: () => ipcRenderer.invoke('check-users-exist'),
  setupAdmin: (data) => ipcRenderer.invoke('setup-admin', data),
  loginUser: (data) => ipcRenderer.invoke('login-user', data),
  registerPendingUser: (data) => ipcRenderer.invoke('register-pending-user', data),
  getPendingAccounts: () => ipcRenderer.invoke('get-pending-accounts'),
  approveAccountRequest: (userId) => ipcRenderer.invoke('approve-account-request', userId),
  denyAccountRequest: (userId) => ipcRenderer.invoke('deny-account-request', userId),
  getAllUsers: () => ipcRenderer.invoke('get-all-users'),
  resetUserPassword: (data) => ipcRenderer.invoke('reset-user-password', data),
  deleteUserAccount: (userId) => ipcRenderer.invoke('delete-user-account', userId),
  updateUserStatus: (data) => ipcRenderer.invoke('update-user-status', data),
  getDbPath: () => ipcRenderer.invoke('db:get-path'),
  selectDbPath: () => ipcRenderer.invoke('db:select-path'),
  reloadDatabase: () => ipcRenderer.invoke('reload-database'),
  // Finance Management
  getFinanceUsers: () => ipcRenderer.invoke('get-finance-users'),
  updateUserFinance: (data) => ipcRenderer.invoke('update-user-finance', data),
  getMonthlyRevenue: (month) => ipcRenderer.invoke('get-monthly-revenue', month),
  getDoctorSessionsCount: (data) => ipcRenderer.invoke('get-doctor-sessions-count', data),
  saveSalaryRecord: (data) => ipcRenderer.invoke('save-salary-record', data),
  getSalaryRecords: (month) => ipcRenderer.invoke('get-salary-records', month),
  // Loans
  addLoan: (data) => ipcRenderer.invoke('add-loan', data),
  getLoans: (month) => ipcRenderer.invoke('get-loans', month),
  deleteLoan: (loanId) => ipcRenderer.invoke('delete-loan', loanId),
  settleLoan: (loanId) => ipcRenderer.invoke('settle-loan', loanId),
  resetLoans: (month) => ipcRenderer.invoke('reset-loans', month),
  // Wastes
  addWasteItem: (data) => ipcRenderer.invoke('add-waste-item', data),
  getWasteItems: (date) => ipcRenderer.invoke('get-waste-items', date),
  deleteWasteItem: (id) => ipcRenderer.invoke('delete-waste-item', id),
  getWasteDays: (month) => ipcRenderer.invoke('get-waste-days', month),
  // Daily Summary
  getDailySummary: (date) => ipcRenderer.invoke('get-daily-summary', date),
  // Doctors list for filters
  getDoctorsList: () => ipcRenderer.invoke('get-doctors-list'),
  getLocalUrl: () => ipcRenderer.invoke('get-local-url'),
  getTailscaleUrl: () => ipcRenderer.invoke('get-tailscale-url'),
  updateActiveSession: (data) => ipcRenderer.invoke('update-active-session', data),
  getActiveSessions: () => ipcRenderer.invoke('get-active-sessions'),
  removeActiveSession: (username) => ipcRenderer.invoke('remove-active-session', username),
  confirm: (message) => ipcRenderer.sendSync('show-confirm-dialog', message),
  // Client Profiles
  getClientProfiles: (clientId) => ipcRenderer.invoke('get-client-profiles', clientId),
  createClientProfile: (data) => ipcRenderer.invoke('create-client-profile', data),
  deleteClientProfile: (profileId) => ipcRenderer.invoke('delete-client-profile', profileId),
  updateClientProfileHeight: (data) => ipcRenderer.invoke('update-client-profile-height', data),
  getClientProfile: (profileId) => ipcRenderer.invoke('get-client-profile', profileId),
  // PT Red Flags
  getPTRedFlags: (profileId) => ipcRenderer.invoke('get-pt-red-flags', profileId),
  savePTRedFlags: (profileId, data) => ipcRenderer.invoke('save-pt-red-flags', profileId, data),
  // PT Subjective
  getPTSubjective: (profileId, subjectiveId) => ipcRenderer.invoke('get-pt-subjective', profileId, subjectiveId),
  getPTSubjectives: (profileId) => ipcRenderer.invoke('get-pt-subjectives', profileId),
  savePTSubjective: (profileId, data) => ipcRenderer.invoke('save-pt-subjective', profileId, data),
  deletePTAssessment: (subjectiveId) => ipcRenderer.invoke('delete-pt-assessment', subjectiveId),
  // PT Objective
  getPTObjectiveRows: (profileId, subjectiveId) => ipcRenderer.invoke('get-pt-objective-rows', profileId, subjectiveId),
  savePTObjectiveRows: (profileId, data) => ipcRenderer.invoke('save-pt-objective-rows', profileId, data),
  getPTPalpation: (profileId, subjectiveId) => ipcRenderer.invoke('get-pt-palpation', profileId, subjectiveId),
  savePTPalpation: (profileId, data) => ipcRenderer.invoke('save-pt-palpation', profileId, data),
  // PT Special Tests
  getPTSpecialTestResults: (profileId) => ipcRenderer.invoke('get-pt-special-test-results', profileId),
  savePTSpecialTestResult: (data) => ipcRenderer.invoke('save-pt-special-test-result', data),
  // PT Session Plan
  getPTSessionPlan: (profileId) => ipcRenderer.invoke('get-pt-session-plan', profileId),
  getPTSessionPlans: (profileId) => ipcRenderer.invoke('get-pt-session-plans', profileId),
  savePTSessionPlan: (profileId, data) => ipcRenderer.invoke('save-pt-session-plan', profileId, data),
  deletePTSessionPlan: (id) => ipcRenderer.invoke('delete-pt-session-plan', id),
  // Nutrition
  getNutritionHistory: (profileId) => ipcRenderer.invoke('get-nutrition-history', profileId),
  addNutritionHistory: (profileId, data) => ipcRenderer.invoke('add-nutrition-history', profileId, data),
  updateNutritionHistory: (id, data) => ipcRenderer.invoke('update-nutrition-history', id, data),
  deleteNutritionHistory: (id) => ipcRenderer.invoke('delete-nutrition-history', id),
  // Investigations
  getInvestigationLibrary: () => ipcRenderer.invoke('get-investigation-library'),
  addToInvestigationLibrary: (name) => ipcRenderer.invoke('add-to-investigation-library', name),
  deleteFromInvestigationLibrary: (id) => ipcRenderer.invoke('delete-from-investigation-library', id),
  getClientInvestigations: (profileId) => ipcRenderer.invoke('get-client-investigations', profileId),
  assignInvestigation: (profileId, investigationId) => ipcRenderer.invoke('assign-investigation', profileId, investigationId),
  updateInvestigationResult: (id, data) => ipcRenderer.invoke('update-investigation-result', id, data),
  removeClientInvestigation: (id) => ipcRenderer.invoke('remove-client-investigation', id),
  // InBody
  uploadInbodyPhoto: (profileId) => ipcRenderer.invoke('upload-inbody-photo', profileId),
  getInbodyUploads: (profileId) => ipcRenderer.invoke('get-inbody-uploads', profileId),
  deleteInbodyUpload: (id) => ipcRenderer.invoke('delete-inbody-upload', id),
  getLymphaticMeasurements: (profileId) => ipcRenderer.invoke('get-lymphatic-measurements', profileId),
  saveLymphaticMeasurement: (profileId, data) => ipcRenderer.invoke('save-lymphatic-measurement', profileId, data),
  deleteLymphaticMeasurement: (id) => ipcRenderer.invoke('delete-lymphatic-measurement', id),
  // Attendance
  clockIn: (data) => ipcRenderer.invoke('clock-in', data),
  clockOut: (data) => ipcRenderer.invoke('clock-out', data),
  getAttendanceLogs: (date) => ipcRenderer.invoke('get-attendance-logs', date),
  // Session Types
  getSessionTypes: () => ipcRenderer.invoke('get-session-types'),
  createSessionType: (data) => ipcRenderer.invoke('create-session-type', data),
  updateSessionType: (id, data) => ipcRenderer.invoke('update-session-type', id, data),
  deleteSessionType: (id) => ipcRenderer.invoke('delete-session-type', id),
  // Home Exercises
  getHomeExercises: (clientId) => ipcRenderer.invoke('get-home-exercises', clientId),
  assignHomeExercise: (data) => ipcRenderer.invoke('assign-home-exercise', data),
  removeHomeExercise: (id) => ipcRenderer.invoke('remove-home-exercise', id),
  updateHomeExercise: (id, data) => ipcRenderer.invoke('update-home-exercise', id, data),
  // Branch Management
  getBranches: () => ipcRenderer.invoke('get-branches'),
  getAllBranches: () => ipcRenderer.invoke('get-all-branches'),
  setCurrentBranch: (branchId) => ipcRenderer.invoke('set-current-branch', branchId),
  getCurrentBranch: () => ipcRenderer.invoke('get-current-branch'),
  addBranch: (name) => ipcRenderer.invoke('add-branch', name),
  renameBranch: (data) => ipcRenderer.invoke('rename-branch', data),
  deactivateBranch: (branchId) => ipcRenderer.invoke('deactivate-branch', branchId),
  reactivateBranch: (branchId) => ipcRenderer.invoke('reactivate-branch', branchId),
});
